-- Resep menu (BOM per 1 porsi) dari sheet HPP menu KBU, minuman KBU, dan HPP Kisamen.
-- Bahan yang belum ada di master (nasi, lalapan, es batu, kemasan per pcs, sambal per porsi, kopi, dll.) belum dimasukkan:
-- lengkapi lewat tab Resep Menu. Baris sheet yang berupa angka batch (teh manis, jengkol, cornmilk, karage topping) dibuang.
-- Aman dijalankan ulang (menu/baris/alias yang sudah ada tidak ditimpa).
begin;

insert into public.inv_menus (business_id, lokasi, nama)
select 'e23ed572-234c-4995-acad-fa6bff7c58d2'::uuid, v.lokasi, v.nama from (values
  ('KBU', 'Ayam Kemangi Ricebowl'),
  ('KBU', 'Cireng'),
  ('KBU', 'Coffe Latte Caramel'),
  ('KBU', 'Coffe Latte Halzenut'),
  ('KBU', 'Coffe Latte Pandan'),
  ('KBU', 'Coffe Latte Salted Caramel'),
  ('KBU', 'Coffe Latte Vanila'),
  ('KBU', 'Cumi Ijo Ricebowl'),
  ('KBU', 'Dimsum'),
  ('KBU', 'Dimsum Mentai'),
  ('KBU', 'FF Normal'),
  ('KBU', 'Green Tea'),
  ('KBU', 'Gyoza'),
  ('KBU', 'Gyoza Mentai'),
  ('KBU', 'Jengkol Pasir'),
  ('KBU', 'Jukut Goreng'),
  ('KBU', 'Karage Ricebowl'),
  ('KBU', 'Katsu Ricebowl'),
  ('KBU', 'Kol Goreng'),
  ('KBU', 'Kopi Capucino'),
  ('KBU', 'Kopi Gula Aren'),
  ('KBU', 'Kopi Jadul'),
  ('KBU', 'Kopsus Burma'),
  ('KBU', 'Kulit Krispi'),
  ('KBU', 'Lauk Ayam Baput'),
  ('KBU', 'Lauk Ayam Besar'),
  ('KBU', 'Lauk Ayam Besar Madura'),
  ('KBU', 'Lauk Ayam Sedeng'),
  ('KBU', 'Lauk Ayam Sedeng Madura'),
  ('KBU', 'Lauk Bebek'),
  ('KBU', 'Lauk Bebek Madura'),
  ('KBU', 'Lauk Ikan Pindang Patin'),
  ('KBU', 'Lauk Lele'),
  ('KBU', 'Lauk Nila'),
  ('KBU', 'Lauk Nila Cobek'),
  ('KBU', 'Lauk Telor Kribo'),
  ('KBU', 'Leci Tea'),
  ('KBU', 'Leci Yakult'),
  ('KBU', 'Lemon Tea'),
  ('KBU', 'Milkshake Avocado'),
  ('KBU', 'Milkshake Greentea'),
  ('KBU', 'Milkshake Red Velvet'),
  ('KBU', 'Milkshake Taro'),
  ('KBU', 'Milkshake Vanila'),
  ('KBU', 'Mojito Blue Coracao'),
  ('KBU', 'Mojito Leci'),
  ('KBU', 'Mojito Lemon'),
  ('KBU', 'Mojito Melon'),
  ('KBU', 'Mojito Strawberry'),
  ('KBU', 'Nasi Bojot'),
  ('KBU', 'Nasi Kemangi Pedas'),
  ('KBU', 'Nasi Koya Pedas'),
  ('KBU', 'Nasi Rempah'),
  ('KBU', 'Otak-otak'),
  ('KBU', 'Panas Ayam Baput'),
  ('KBU', 'Panas Ayam Baput Madura'),
  ('KBU', 'Panas Ayam Besar'),
  ('KBU', 'Panas Ayam Besar Madura'),
  ('KBU', 'Panas Ayam Sedeng'),
  ('KBU', 'Panas Ayam Sedeng Madura'),
  ('KBU', 'Panas Bebek'),
  ('KBU', 'Panas Bebek Madura'),
  ('KBU', 'Panas Lele'),
  ('KBU', 'Panas Nila'),
  ('KBU', 'Pecok Katel'),
  ('KBU', 'Pisang Goreng Keju'),
  ('KBU', 'Pisang Goreng Pasir'),
  ('KBU', 'Plater Premium'),
  ('KBU', 'Plater Standar'),
  ('KBU', 'Sosis Solo'),
  ('KBU', 'Tahu Cabe Garam'),
  ('KBU', 'Tempong Ayam Baput'),
  ('KBU', 'Tempong Ayam Besar'),
  ('KBU', 'Tempong Bebek'),
  ('KBU', 'Tempong Lele'),
  ('KBU', 'Tempong Nila'),
  ('KBU', 'Tempong Telor Kribo'),
  ('KBU', 'Thai Tea'),
  ('KSM', 'Bakmi Imperial'),
  ('KSM', 'Beef Yakiniku Donburi'),
  ('KSM', 'Chicken Katsu'),
  ('KSM', 'Chicken Ricebowl'),
  ('KSM', 'Corn Milk'),
  ('KSM', 'Corn Milk Coffe Latte'),
  ('KSM', 'Corn Milk Matcha'),
  ('KSM', 'Corn Ribs'),
  ('KSM', 'Dimsum Mentai'),
  ('KSM', 'Enoki Takiage'),
  ('KSM', 'Gyoza Mentai'),
  ('KSM', 'Leci Ice'),
  ('KSM', 'Lemontea'),
  ('KSM', 'Manggo Ice'),
  ('KSM', 'Mentai Donburi'),
  ('KSM', 'Milo Ice'),
  ('KSM', 'Mix Plater'),
  ('KSM', 'Orange Ice'),
  ('KSM', 'Ramen Atomic'),
  ('KSM', 'Ramen Chesee Creamy'),
  ('KSM', 'Ramen Curry Original'),
  ('KSM', 'Ramen Curry Spicy'),
  ('KSM', 'Ramen Hashirama Standar'),
  ('KSM', 'Ramen Madara Standar'),
  ('KSM', 'Ramen Miso'),
  ('KSM', 'Ramen Shoyu Standar'),
  ('KSM', 'Ramen Tantamen'),
  ('KSM', 'Ramen Toripaitan Standar'),
  ('KSM', 'Ramen Truffle'),
  ('KSM', 'Shukaku Puding'),
  ('KSM', 'Stadard Dry Ramen'),
  ('KSM', 'Strawberry Kisamatcha Lattte'),
  ('KSM', 'Teh Manis'),
  ('KSM', 'Teh Tarik'),
  ('KSM', 'Tori Rice'),
  ('KSM', 'Ubee Coffe Latte'),
  ('KSM', 'Ubee Creamy Thaitea')
) as v(lokasi, nama)
on conflict do nothing;

insert into public.inv_menu_lines (menu_id, business_id, item_id, qty, qty_input, satuan_input, urut)
select m.id, m.business_id, i.id, v.qty, v.qty_input, v.satuan_input, v.urut from (values
  ('KBU', 'Ayam Kemangi Ricebowl', 'AYMKMG', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Ayam Kemangi Ricebowl', 'TLR', 1.0, 1.0, 'btr', 1),
  ('KBU', 'Ayam Kemangi Ricebowl', 'MINGOR', 20.0, 20.0, 'ml', 2),
  ('KBU', 'Cireng', 'CRNG', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Cireng', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Cireng', 'DELTOM', 0.001, 1.0, 'gr', 2),
  ('KBU', 'Coffe Latte Caramel', 'SUSFRES', 0.1, 100.0, 'ml', 0),
  ('KBU', 'Coffe Latte Halzenut', 'SUSFRES', 0.1, 100.0, 'ml', 0),
  ('KBU', 'Coffe Latte Pandan', 'SUSFRES', 0.1, 100.0, 'ml', 0),
  ('KBU', 'Coffe Latte Salted Caramel', 'SUSFRES', 0.1, 100.0, 'ml', 0),
  ('KBU', 'Coffe Latte Vanila', 'SRPVNL', 0.03913, 18.0, 'ml', 0),
  ('KBU', 'Coffe Latte Vanila', 'SUSFRES', 0.1, 100.0, 'ml', 1),
  ('KBU', 'Cumi Ijo Ricebowl', 'CMIJO', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Cumi Ijo Ricebowl', 'TLR', 1.0, 1.0, 'btr', 1),
  ('KBU', 'Cumi Ijo Ricebowl', 'MINGOR', 20.0, 20.0, 'ml', 2),
  ('KBU', 'Dimsum', 'DIMSUM', 6.0, 6.0, 'pcs', 0),
  ('KBU', 'Dimsum', 'FOIL DIM', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Dimsum Mentai', 'DIMSUM', 6.0, 6.0, 'pcs', 0),
  ('KBU', 'Dimsum Mentai', 'FOIL DIM', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'FF Normal', 'KNTG', 125.0, 125.0, 'gr', 0),
  ('KBU', 'FF Normal', 'DELCHIL', 0.03, 30.0, 'gr', 1),
  ('KBU', 'FF Normal', 'MINGOR', 30.0, 30.0, 'ml', 2),
  ('KBU', 'Green Tea', 'POWGT', 45.0, 45.0, 'gr', 0),
  ('KBU', 'Green Tea', 'SKM', 0.04, 40.0, 'gr', 1),
  ('KBU', 'Green Tea', 'SUSFRES', 0.02, 20.0, 'ml', 2),
  ('KBU', 'Gyoza', 'GYOZA', 6.0, 6.0, 'pcs', 0),
  ('KBU', 'Gyoza', 'FOIL DIM', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Gyoza Mentai', 'GYOZA', 6.0, 6.0, 'pcs', 0),
  ('KBU', 'Gyoza Mentai', 'FOIL DIM', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Jengkol Pasir', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Jengkol Pasir', 'BAPUTG', 7.0, 7.0, 'gr', 2),
  ('KBU', 'Jengkol Pasir', 'SAYAM', 3.0, 3.0, 'gr', 3),
  ('KBU', 'Jukut Goreng', 'JKUT', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Jukut Goreng', 'MINGOR', 40.0, 40.0, 'ml', 1),
  ('KBU', 'Jukut Goreng', 'BAPUTG', 7.0, 7.0, 'gr', 2),
  ('KBU', 'Jukut Goreng', 'SAYAM', 2.0, 2.0, 'gr', 3),
  ('KBU', 'Karage Ricebowl', 'KRGE', 60.0, 60.0, 'gr', 0),
  ('KBU', 'Karage Ricebowl', 'DELBBQ', 0.02, 20.0, 'gr', 1),
  ('KBU', 'Karage Ricebowl', 'TLR', 1.0, 1.0, 'btr', 2),
  ('KBU', 'Karage Ricebowl', 'MINGOR', 40.0, 40.0, 'ml', 3),
  ('KBU', 'Katsu Ricebowl', 'KTSU', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Katsu Ricebowl', 'DELBBQ', 0.02, 20.0, 'gr', 1),
  ('KBU', 'Katsu Ricebowl', 'MINGOR', 30.0, 30.0, 'ml', 2),
  ('KBU', 'Katsu Ricebowl', 'WIJEN', 1.0, 1.0, 'gr', 3),
  ('KBU', 'Kol Goreng', 'MINGOR', 30.0, 30.0, 'ml', 0),
  ('KBU', 'Kopi Capucino', 'GLAC', 20.0, 20.0, 'ml', 0),
  ('KBU', 'Kopi Capucino', 'SUSFRES', 0.1, 100.0, 'ml', 1),
  ('KBU', 'Kopi Gula Aren', 'GLAC', 20.0, 20.0, 'ml', 0),
  ('KBU', 'Kopi Gula Aren', 'SUSFRES', 0.08, 80.0, 'ml', 1),
  ('KBU', 'Kopi Jadul', 'SKM', 0.02, 20.0, 'gr', 0),
  ('KBU', 'Kopi Jadul', 'SUSFRES', 0.1, 100.0, 'ml', 1),
  ('KBU', 'Kopsus Burma', 'CREMPREM', 8.0, 8.0, 'gr', 0),
  ('KBU', 'Kopsus Burma', 'GLAC', 5.0, 5.0, 'ml', 1),
  ('KBU', 'Kopsus Burma', 'SRPVNL', 0.01087, 5.0, 'ml', 2),
  ('KBU', 'Kulit Krispi', 'KULKRISPI', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Lauk Ayam Baput', 'AYMBPT', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Lauk Ayam Baput', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Lauk Ayam Baput', 'BWP', 5.0, 5.0, 'gr', 2),
  ('KBU', 'Lauk Ayam Besar', 'AYMBSR', 1.0, 1.0, 'ptng', 0),
  ('KBU', 'Lauk Ayam Besar', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Lauk Ayam Besar Madura', 'AYMBSR', 1.0, 1.0, 'ptng', 0),
  ('KBU', 'Lauk Ayam Besar Madura', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Lauk Ayam Sedeng', 'AYMSDG', 1.0, 1.0, 'ptng', 0),
  ('KBU', 'Lauk Ayam Sedeng', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Lauk Ayam Sedeng Madura', 'AYMSDG', 1.0, 1.0, 'ptng', 0),
  ('KBU', 'Lauk Ayam Sedeng Madura', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Lauk Bebek', 'BBK', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Lauk Bebek', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Lauk Bebek Madura', 'BBK', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Lauk Bebek Madura', 'TMPE', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Lauk Bebek Madura', 'THU', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Lauk Bebek Madura', 'MINGOR', 30.0, 30.0, 'ml', 3),
  ('KBU', 'Lauk Ikan Pindang Patin', 'IKNPTN', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Lauk Lele', 'IKNLL', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Lauk Lele', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Lauk Nila', 'IKNNL', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Lauk Nila', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Lauk Nila Cobek', 'IKNNL', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Lauk Nila Cobek', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Lauk Telor Kribo', 'TLR', 1.0, 1.0, 'btr', 0),
  ('KBU', 'Lauk Telor Kribo', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Lauk Telor Kribo', 'TRGU', 50.0, 50.0, 'gr', 2),
  ('KBU', 'Lauk Telor Kribo', 'SAYAM', 2.0, 2.0, 'gr', 3),
  ('KBU', 'Leci Tea', 'GULCAIR', 10.0, 10.0, 'ml', 0),
  ('KBU', 'Leci Tea', 'LPTN LC', 1.0, 15.0, 'gr', 1),
  ('KBU', 'Leci Yakult', 'YAKULT', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Leci Yakult', 'SRPLCMJN', 0.036957, 17.0, 'ml', 1),
  ('KBU', 'Lemon Tea', 'GULCAIR', 10.0, 10.0, 'ml', 0),
  ('KBU', 'Lemon Tea', 'LPTN LMN', 1.0, 15.0, 'gr', 1),
  ('KBU', 'Milkshake Avocado', 'POWAVCD', 15.0, 15.0, 'gr', 0),
  ('KBU', 'Milkshake Avocado', 'GULCAIR', 20.0, 20.0, 'ml', 1),
  ('KBU', 'Milkshake Avocado', 'SUSFRES', 0.08, 80.0, 'ml', 2),
  ('KBU', 'Milkshake Greentea', 'POWGT', 15.0, 15.0, 'gr', 0),
  ('KBU', 'Milkshake Greentea', 'GULCAIR', 1.0, 1.0, 'ml', 1),
  ('KBU', 'Milkshake Greentea', 'SUSFRES', 0.08, 80.0, 'ml', 2),
  ('KBU', 'Milkshake Red Velvet', 'POWRV', 15.0, 15.0, 'gr', 0),
  ('KBU', 'Milkshake Red Velvet', 'GULCAIR', 20.0, 20.0, 'ml', 1),
  ('KBU', 'Milkshake Red Velvet', 'SUSFRES', 0.08, 80.0, 'ml', 2),
  ('KBU', 'Milkshake Taro', 'POWTR', 15.0, 15.0, 'gr', 0),
  ('KBU', 'Milkshake Taro', 'GULCAIR', 1.0, 1.0, 'ml', 1),
  ('KBU', 'Milkshake Taro', 'SUSFRES', 0.08, 80.0, 'ml', 2),
  ('KBU', 'Milkshake Vanila', 'GULCAIR', 1.0, 1.0, 'ml', 0),
  ('KBU', 'Milkshake Vanila', 'SUSFRES', 0.08, 80.0, 'ml', 1),
  ('KBU', 'Mojito Blue Coracao', 'SLSH', 1.0, 1.0, 'gr', 0),
  ('KBU', 'Mojito Leci', 'SRPLCMJN', 0.03913, 18.0, 'ml', 0),
  ('KBU', 'Mojito Leci', 'SLSH', 1.0, 1.0, 'gr', 1),
  ('KBU', 'Mojito Lemon', 'SLSH', 1.0, 1.0, 'gr', 0),
  ('KBU', 'Mojito Melon', 'SRPMLN', 0.03913, 18.0, 'ml', 0),
  ('KBU', 'Mojito Melon', 'SLSH', 1.0, 1.0, 'gr', 1),
  ('KBU', 'Mojito Strawberry', 'SRPSTRWB', 0.03913, 18.0, 'ml', 0),
  ('KBU', 'Mojito Strawberry', 'SLSH', 1.0, 1.0, 'gr', 1),
  ('KBU', 'Nasi Bojot', 'MINBAWANG', 10.0, 10.0, 'ml', 0),
  ('KBU', 'Nasi Koya Pedas', 'BAPUTG', 5.0, 5.0, 'gr', 0),
  ('KBU', 'Nasi Koya Pedas', 'MINBAWANG', 10.0, 10.0, 'ml', 1),
  ('KBU', 'Otak-otak', 'OTKOTK', 10.0, 10.0, 'pcs', 0),
  ('KBU', 'Otak-otak', 'DELCHIL', 0.03, 30.0, 'gr', 1),
  ('KBU', 'Otak-otak', 'MINGOR', 30.0, 30.0, 'ml', 2),
  ('KBU', 'Panas Ayam Baput', 'AYMBPT', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Panas Ayam Baput', 'THU', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Panas Ayam Baput', 'TMPE', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Panas Ayam Baput', 'BWP', 5.0, 5.0, 'gr', 3),
  ('KBU', 'Panas Ayam Baput', 'MINGOR', 30.0, 30.0, 'ml', 4),
  ('KBU', 'Panas Ayam Baput Madura', 'AYMBPT', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Panas Ayam Baput Madura', 'TMPE', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Panas Ayam Baput Madura', 'THU', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Panas Ayam Baput Madura', 'BWP', 10.0, 10.0, 'gr', 3),
  ('KBU', 'Panas Ayam Baput Madura', 'MINGOR', 30.0, 30.0, 'ml', 4),
  ('KBU', 'Panas Ayam Besar', 'AYMBSR', 1.0, 1.0, 'ptng', 0),
  ('KBU', 'Panas Ayam Besar', 'THU', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Panas Ayam Besar', 'TMPE', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Panas Ayam Besar', 'MINGOR', 30.0, 30.0, 'ml', 3),
  ('KBU', 'Panas Ayam Besar Madura', 'AYMBSR', 1.0, 1.0, 'ptng', 0),
  ('KBU', 'Panas Ayam Besar Madura', 'TMPE', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Panas Ayam Besar Madura', 'THU', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Panas Ayam Besar Madura', 'MINGOR', 30.0, 30.0, 'ml', 3),
  ('KBU', 'Panas Ayam Sedeng', 'AYMSDG', 1.0, 1.0, 'ptng', 0),
  ('KBU', 'Panas Ayam Sedeng', 'THU', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Panas Ayam Sedeng', 'TMPE', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Panas Ayam Sedeng', 'MINGOR', 30.0, 30.0, 'ml', 3),
  ('KBU', 'Panas Ayam Sedeng Madura', 'AYMSDG', 1.0, 1.0, 'ptng', 0),
  ('KBU', 'Panas Ayam Sedeng Madura', 'TMPE', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Panas Ayam Sedeng Madura', 'THU', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Panas Ayam Sedeng Madura', 'MINGOR', 30.0, 30.0, 'ml', 3),
  ('KBU', 'Panas Bebek', 'BBK', 1.0, 1.0, 'ptng', 0),
  ('KBU', 'Panas Bebek', 'THU', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Panas Bebek', 'TMPE', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Panas Bebek', 'MINGOR', 30.0, 30.0, 'ml', 3),
  ('KBU', 'Panas Bebek Madura', 'BBK', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Panas Bebek Madura', 'TMPE', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Panas Bebek Madura', 'THU', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Panas Bebek Madura', 'MINGOR', 30.0, 30.0, 'ml', 3),
  ('KBU', 'Panas Lele', 'IKNLL', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Panas Lele', 'TMPE', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Panas Lele', 'THU', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Panas Lele', 'MINGOR', 30.0, 30.0, 'ml', 3),
  ('KBU', 'Panas Nila', 'IKNNL', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Panas Nila', 'THU', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Panas Nila', 'TMPE', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Panas Nila', 'MINGOR', 30.0, 30.0, 'ml', 3),
  ('KBU', 'Pisang Goreng Keju', 'SKM', 0.01, 10.0, 'gr', 0),
  ('KBU', 'Pisang Goreng Keju', 'MINGOR', 50.0, 50.0, 'ml', 1),
  ('KBU', 'Pisang Goreng Pasir', 'MINGOR', 50.0, 50.0, 'ml', 0),
  ('KBU', 'Pisang Goreng Pasir', 'GLAB', 10.0, 10.0, 'gr', 1),
  ('KBU', 'Plater Premium', 'KNTG', 75.0, 75.0, 'gr', 0),
  ('KBU', 'Plater Premium', 'SOSDBD', 2.0, 2.0, 'pcs', 1),
  ('KBU', 'Plater Premium', 'KRGE', 30.0, 30.0, 'gr', 2),
  ('KBU', 'Plater Premium', 'NGTMBL', 3.0, 3.0, 'pcs', 3),
  ('KBU', 'Plater Premium', 'DELCHIL', 0.03, 30.0, 'gr', 4),
  ('KBU', 'Plater Premium', 'MINGOR', 30.0, 30.0, 'ml', 5),
  ('KBU', 'Plater Standar', 'KNTG', 75.0, 75.0, 'gr', 0),
  ('KBU', 'Plater Standar', 'OTKOTK', 3.0, 3.0, 'pcs', 1),
  ('KBU', 'Plater Standar', 'SOSDBD', 2.0, 2.0, 'pcs', 2),
  ('KBU', 'Plater Standar', 'DELCHIL', 0.03, 30.0, 'gr', 3),
  ('KBU', 'Plater Standar', 'MINGOR', 30.0, 30.0, 'ml', 4),
  ('KBU', 'Sosis Solo', 'DELCHIL', 0.03, 30.0, 'gr', 0),
  ('KBU', 'Sosis Solo', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Tahu Cabe Garam', 'TAHUCG', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Tahu Cabe Garam', 'CRS', 10.0, 10.0, 'gr', 1),
  ('KBU', 'Tahu Cabe Garam', 'SAYAM', 5.0, 5.0, 'gr', 2),
  ('KBU', 'Tahu Cabe Garam', 'MINGOR', 30.0, 30.0, 'ml', 3),
  ('KBU', 'Tahu Cabe Garam', 'BAPUTG', 10.0, 10.0, 'gr', 4),
  ('KBU', 'Tempong Ayam Baput', 'AYMBPT', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Tempong Ayam Baput', 'THU', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Tempong Ayam Baput', 'TMPE', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Tempong Ayam Baput', 'MINGOR', 50.0, 50.0, 'ml', 3),
  ('KBU', 'Tempong Ayam Besar', 'AYMSDG', 1.0, 1.0, 'ptng', 0),
  ('KBU', 'Tempong Ayam Besar', 'THU', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Tempong Ayam Besar', 'TMPE', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Tempong Ayam Besar', 'MINGOR', 50.0, 50.0, 'ml', 3),
  ('KBU', 'Tempong Bebek', 'BBK', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Tempong Bebek', 'THU', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Tempong Bebek', 'TMPE', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Tempong Bebek', 'MINGOR', 50.0, 50.0, 'ml', 3),
  ('KBU', 'Tempong Lele', 'IKNLL', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Tempong Lele', 'TMPE', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Tempong Lele', 'THU', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Tempong Lele', 'MINGOR', 50.0, 50.0, 'ml', 3),
  ('KBU', 'Tempong Nila', 'IKNNL', 1.0, 1.0, 'pcs', 0),
  ('KBU', 'Tempong Nila', 'THU', 1.0, 1.0, 'pcs', 1),
  ('KBU', 'Tempong Nila', 'TMPE', 1.0, 1.0, 'pcs', 2),
  ('KBU', 'Tempong Nila', 'MINGOR', 50.0, 50.0, 'ml', 3),
  ('KBU', 'Tempong Telor Kribo', 'TLR', 1.0, 1.0, 'btr', 0),
  ('KBU', 'Tempong Telor Kribo', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KBU', 'Tempong Telor Kribo', 'TRGU', 50.0, 50.0, 'gr', 2),
  ('KBU', 'Tempong Telor Kribo', 'SAYAM', 2.0, 2.0, 'gr', 3),
  ('KBU', 'Tempong Telor Kribo', 'TMPE', 1.0, 1.0, 'pcs', 4),
  ('KBU', 'Tempong Telor Kribo', 'THU', 1.0, 1.0, 'pcs', 5),
  ('KBU', 'Thai Tea', 'POWTT', 45.0, 45.0, 'gr', 0),
  ('KBU', 'Thai Tea', 'SKM', 0.04, 40.0, 'gr', 1),
  ('KBU', 'Thai Tea', 'SUSFRES', 0.02, 20.0, 'ml', 2),
  ('KSM', 'Bakmi Imperial', 'MIE', 0.07, 70.0, 'gr', 0),
  ('KSM', 'Bakmi Imperial', 'MINDBWG', 5.0, 5.0, 'ml', 1),
  ('KSM', 'Bakmi Imperial', 'KECAS', 0.005, 3.0, 'ml', 2),
  ('KSM', 'Bakmi Imperial', 'KECAM', 0.008333, 5.0, 'ml', 3),
  ('KSM', 'Bakmi Imperial', 'LDA', 1.0, 1.0, 'gr', 4),
  ('KSM', 'Bakmi Imperial', 'GARLICPWD', 2.0, 2.0, 'gr', 5),
  ('KSM', 'Bakmi Imperial', 'KNORAY', 0.007, 7.0, 'gr', 6),
  ('KSM', 'Bakmi Imperial', 'DBWG', 4.0, 4.0, 'gr', 7),
  ('KSM', 'Beef Yakiniku Donburi', 'BEEF', 50.0, 50.0, 'gr', 0),
  ('KSM', 'Beef Yakiniku Donburi', 'GIMBORI', 5.0, 5.0, 'gr', 1),
  ('KSM', 'Chicken Katsu', 'DELBBQ', 0.02, 20.0, 'gr', 0),
  ('KSM', 'Chicken Katsu', 'MINGOR', 30.0, 30.0, 'ml', 1),
  ('KSM', 'Chicken Katsu', 'WIJEN', 1.0, 1.0, 'gr', 2),
  ('KSM', 'Chicken Ricebowl', 'KRGE', 60.0, 60.0, 'gr', 0),
  ('KSM', 'Chicken Ricebowl', 'DELBBQ', 0.02, 20.0, 'gr', 1),
  ('KSM', 'Chicken Ricebowl', 'MINGOR', 40.0, 40.0, 'ml', 2),
  ('KSM', 'Corn Milk Matcha', 'MATCHACER', 3.0, 3.0, 'gr', 1),
  ('KSM', 'Corn Milk Matcha', 'SUSFRES', 0.04, 40.0, 'ml', 2),
  ('KSM', 'Corn Ribs', 'JAGUNG', 0.25, 250.0, 'gr', 0),
  ('KSM', 'Corn Ribs', 'SAYAM', 5.0, 5.0, 'gr', 1),
  ('KSM', 'Enoki Takiage', 'TRGU', 15.0, 15.0, 'gr', 0),
  ('KSM', 'Leci Ice', 'GULCAIR', 20.0, 20.0, 'ml', 0),
  ('KSM', 'Lemontea', 'LPTN LMN', 1.0, 15.0, 'gr', 0),
  ('KSM', 'Lemontea', 'GULCAIR', 20.0, 20.0, 'ml', 1),
  ('KSM', 'Manggo Ice', 'GULCAIR', 20.0, 20.0, 'ml', 0),
  ('KSM', 'Mentai Donburi', 'GIMBORI', 5.0, 5.0, 'gr', 0),
  ('KSM', 'Milo Ice', 'GULCAIR', 5.0, 5.0, 'ml', 0),
  ('KSM', 'Milo Ice', 'MILO', 1.0, 1.0, 'pcs', 1),
  ('KSM', 'Mix Plater', 'EKADO', 1.0, 1.0, 'pcs', 0),
  ('KSM', 'Orange Ice', 'GULCAIR', 20.0, 20.0, 'ml', 0),
  ('KSM', 'Ramen Atomic', 'MINDBWG', 5.0, 5.0, 'ml', 0),
  ('KSM', 'Ramen Atomic', 'MISO', 7.0, 7.0, 'gr', 1),
  ('KSM', 'Ramen Atomic', 'SHIOTARE', 11.0, 11.0, 'ml', 2),
  ('KSM', 'Ramen Atomic', 'BATOMIC', 0.025, 25.0, 'gr', 3),
  ('KSM', 'Ramen Atomic', 'MIE', 0.07, 70.0, 'gr', 4),
  ('KSM', 'Ramen Atomic', 'JAGUNG', 0.01, 10.0, 'gr', 5),
  ('KSM', 'Ramen Atomic', 'JMRKUPING', 0.01, 10.0, 'gr', 6),
  ('KSM', 'Ramen Atomic', 'DBWG', 4.0, 4.0, 'gr', 7),
  ('KSM', 'Ramen Atomic', 'PKCY', 4.0, 4.0, 'gr', 8),
  ('KSM', 'Ramen Atomic', 'CRS', 2.0, 2.0, 'gr', 9),
  ('KSM', 'Ramen Atomic', 'AJITAMA', 0.5, 0.5, 'pcs', 10),
  ('KSM', 'Ramen Chesee Creamy', 'KEJUKER', 0.01, 10.0, 'gr', 0),
  ('KSM', 'Ramen Chesee Creamy', 'MINDBWG', 5.0, 5.0, 'ml', 1),
  ('KSM', 'Ramen Chesee Creamy', 'CREMPREM', 4.0, 4.0, 'gr', 2),
  ('KSM', 'Ramen Chesee Creamy', 'ATOOM', 0.01, 5.0, 'gr', 3),
  ('KSM', 'Ramen Chesee Creamy', 'MACHIATO CC', 0.004, 4.0, 'gr', 4),
  ('KSM', 'Ramen Chesee Creamy', 'MIE', 0.07, 70.0, 'gr', 5),
  ('KSM', 'Ramen Chesee Creamy', 'JAGUNG', 0.01, 10.0, 'gr', 6),
  ('KSM', 'Ramen Chesee Creamy', 'JMRKUPING', 0.01, 10.0, 'gr', 7),
  ('KSM', 'Ramen Chesee Creamy', 'DBWG', 4.0, 4.0, 'gr', 8),
  ('KSM', 'Ramen Chesee Creamy', 'PKCY', 5.0, 5.0, 'gr', 9),
  ('KSM', 'Ramen Chesee Creamy', 'AJITAMA', 0.5, 0.5, 'pcs', 10),
  ('KSM', 'Ramen Curry Original', 'CURRYORI', 15.0, 15.0, 'gr', 0),
  ('KSM', 'Ramen Curry Original', 'SHIOTARE', 11.0, 11.0, 'ml', 1),
  ('KSM', 'Ramen Curry Original', 'MINDBWG', 5.0, 5.0, 'ml', 2),
  ('KSM', 'Ramen Curry Original', 'MIE', 0.07, 70.0, 'gr', 3),
  ('KSM', 'Ramen Curry Original', 'AJITAMA', 0.5, 0.5, 'pcs', 4),
  ('KSM', 'Ramen Curry Original', 'JAGUNG', 0.01, 10.0, 'gr', 5),
  ('KSM', 'Ramen Curry Original', 'JMRKUPING', 0.01, 10.0, 'gr', 6),
  ('KSM', 'Ramen Curry Original', 'DBWG', 4.0, 4.0, 'gr', 7),
  ('KSM', 'Ramen Curry Original', 'PKCY', 5.0, 5.0, 'gr', 8),
  ('KSM', 'Ramen Curry Spicy', 'CURRYSPICY', 15.0, 15.0, 'gr', 0),
  ('KSM', 'Ramen Curry Spicy', 'SHIOTARE', 11.0, 11.0, 'ml', 1),
  ('KSM', 'Ramen Curry Spicy', 'MINDBWG', 5.0, 5.0, 'ml', 2),
  ('KSM', 'Ramen Curry Spicy', 'CHILIOIL', 0.002, 2.0, 'ml', 3),
  ('KSM', 'Ramen Curry Spicy', 'MIE', 0.07, 70.0, 'gr', 4),
  ('KSM', 'Ramen Curry Spicy', 'AJITAMA', 0.5, 0.5, 'pcs', 5),
  ('KSM', 'Ramen Curry Spicy', 'JAGUNG', 0.01, 10.0, 'gr', 6),
  ('KSM', 'Ramen Curry Spicy', 'JMRKUPING', 0.01, 10.0, 'gr', 7),
  ('KSM', 'Ramen Curry Spicy', 'DBWG', 4.0, 4.0, 'gr', 8),
  ('KSM', 'Ramen Curry Spicy', 'PKCY', 5.0, 5.0, 'gr', 9),
  ('KSM', 'Ramen Hashirama Standar', 'MINDBWG', 5.0, 5.0, 'ml', 0),
  ('KSM', 'Ramen Hashirama Standar', 'MISO', 7.0, 7.0, 'gr', 1),
  ('KSM', 'Ramen Hashirama Standar', 'SHIOTARE', 11.0, 11.0, 'ml', 2),
  ('KSM', 'Ramen Hashirama Standar', 'SHOYUTARE', 11.0, 11.0, 'ml', 3),
  ('KSM', 'Ramen Hashirama Standar', 'BHASHIRAMA', 25.0, 25.0, 'gr', 4),
  ('KSM', 'Ramen Hashirama Standar', 'JAGUNG', 0.01, 10.0, 'gr', 5),
  ('KSM', 'Ramen Hashirama Standar', 'JMRKUPING', 0.01, 10.0, 'gr', 6),
  ('KSM', 'Ramen Hashirama Standar', 'DBWG', 4.0, 4.0, 'gr', 7),
  ('KSM', 'Ramen Hashirama Standar', 'MIE', 0.07, 70.0, 'gr', 8),
  ('KSM', 'Ramen Hashirama Standar', 'AJITAMA', 0.5, 0.5, 'pcs', 9),
  ('KSM', 'Ramen Hashirama Standar', 'PKCY', 5.0, 5.0, 'gr', 10),
  ('KSM', 'Ramen Madara Standar', 'MINDBWG', 5.0, 5.0, 'ml', 0),
  ('KSM', 'Ramen Madara Standar', 'MISO', 7.0, 7.0, 'gr', 1),
  ('KSM', 'Ramen Madara Standar', 'SHIOTARE', 11.0, 11.0, 'ml', 2),
  ('KSM', 'Ramen Madara Standar', 'SHOYUTARE', 11.0, 11.0, 'ml', 3),
  ('KSM', 'Ramen Madara Standar', 'BMADARA', 0.025, 25.0, 'gr', 4),
  ('KSM', 'Ramen Madara Standar', 'MIE', 0.07, 70.0, 'gr', 5),
  ('KSM', 'Ramen Madara Standar', 'JAGUNG', 0.01, 10.0, 'gr', 6),
  ('KSM', 'Ramen Madara Standar', 'JMRKUPING', 0.01, 10.0, 'gr', 7),
  ('KSM', 'Ramen Madara Standar', 'DBWG', 4.0, 4.0, 'gr', 8),
  ('KSM', 'Ramen Madara Standar', 'PKCY', 4.0, 4.0, 'gr', 9),
  ('KSM', 'Ramen Madara Standar', 'AJITAMA', 0.5, 0.5, 'pcs', 10),
  ('KSM', 'Ramen Miso', 'SHIOTARE', 11.0, 11.0, 'ml', 0),
  ('KSM', 'Ramen Miso', 'SHOYUTARE', 11.0, 11.0, 'ml', 1),
  ('KSM', 'Ramen Miso', 'MINDBWG', 5.0, 5.0, 'ml', 2),
  ('KSM', 'Ramen Miso', 'ATOOM', 0.004, 2.0, 'gr', 3),
  ('KSM', 'Ramen Miso', 'MISO', 7.0, 7.0, 'gr', 4),
  ('KSM', 'Ramen Miso', 'BMISO', 10.0, 10.0, 'gr', 5),
  ('KSM', 'Ramen Miso', 'MIE', 0.07, 70.0, 'gr', 6),
  ('KSM', 'Ramen Miso', 'JAGUNG', 0.01, 10.0, 'gr', 7),
  ('KSM', 'Ramen Miso', 'JMRKUPING', 0.01, 10.0, 'gr', 8),
  ('KSM', 'Ramen Miso', 'DBWG', 4.0, 4.0, 'gr', 9),
  ('KSM', 'Ramen Miso', 'PKCY', 5.0, 5.0, 'gr', 10),
  ('KSM', 'Ramen Miso', 'AJITAMA', 0.5, 0.5, 'pcs', 11),
  ('KSM', 'Ramen Shoyu Standar', 'MINDBWG', 5.0, 5.0, 'ml', 0),
  ('KSM', 'Ramen Shoyu Standar', 'SHIOTARE', 11.0, 11.0, 'ml', 1),
  ('KSM', 'Ramen Shoyu Standar', 'CHASHU', 0.001, 1.0, 'gr', 2),
  ('KSM', 'Ramen Shoyu Standar', 'BSHOYU', 22.0, 22.0, 'ml', 3),
  ('KSM', 'Ramen Shoyu Standar', 'DBWG', 4.0, 4.0, 'gr', 4),
  ('KSM', 'Ramen Shoyu Standar', 'MIE', 0.07, 70.0, 'gr', 5),
  ('KSM', 'Ramen Shoyu Standar', 'JAGUNG', 0.01, 10.0, 'gr', 6),
  ('KSM', 'Ramen Shoyu Standar', 'JMRKUPING', 0.01, 10.0, 'gr', 7),
  ('KSM', 'Ramen Shoyu Standar', 'PKCY', 5.0, 5.0, 'gr', 8),
  ('KSM', 'Ramen Shoyu Standar', 'AJITAMA', 0.5, 0.5, 'pcs', 9),
  ('KSM', 'Ramen Tantamen', 'MINDBWG', 5.0, 5.0, 'ml', 0),
  ('KSM', 'Ramen Tantamen', 'MISO', 7.0, 7.0, 'gr', 1),
  ('KSM', 'Ramen Tantamen', 'CREMPREM', 4.0, 4.0, 'gr', 2),
  ('KSM', 'Ramen Tantamen', 'SUSFRES', 0.022, 22.0, 'ml', 3),
  ('KSM', 'Ramen Tantamen', 'SHIOTARE', 11.0, 11.0, 'ml', 4),
  ('KSM', 'Ramen Tantamen', 'SHOYUTARE', 11.0, 11.0, 'ml', 5),
  ('KSM', 'Ramen Tantamen', 'CHILIOIL', 0.002, 2.0, 'ml', 6),
  ('KSM', 'Ramen Tantamen', 'MIE', 0.07, 70.0, 'gr', 7),
  ('KSM', 'Ramen Tantamen', 'BTANTAMEN', 10.0, 10.0, 'gr', 8),
  ('KSM', 'Ramen Tantamen', 'JAGUNG', 0.01, 10.0, 'gr', 9),
  ('KSM', 'Ramen Tantamen', 'JMRKUPING', 0.01, 10.0, 'gr', 10),
  ('KSM', 'Ramen Tantamen', 'DBWG', 4.0, 4.0, 'gr', 11),
  ('KSM', 'Ramen Tantamen', 'PKCY', 5.0, 5.0, 'gr', 12),
  ('KSM', 'Ramen Tantamen', 'AJITAMA', 0.5, 0.5, 'pcs', 13),
  ('KSM', 'Ramen Toripaitan Standar', 'MINDBWG', 5.0, 5.0, 'ml', 0),
  ('KSM', 'Ramen Toripaitan Standar', 'SHIOTARE', 11.0, 11.0, 'ml', 1),
  ('KSM', 'Ramen Toripaitan Standar', 'SHOYUTARE', 11.0, 11.0, 'ml', 2),
  ('KSM', 'Ramen Toripaitan Standar', 'BPAITAN', 0.014, 14.0, 'gr', 3),
  ('KSM', 'Ramen Toripaitan Standar', 'SUSFRES', 0.03, 30.0, 'ml', 4),
  ('KSM', 'Ramen Toripaitan Standar', 'MIE', 0.07, 70.0, 'gr', 5),
  ('KSM', 'Ramen Toripaitan Standar', 'JAGUNG', 0.01, 10.0, 'gr', 6),
  ('KSM', 'Ramen Toripaitan Standar', 'AJITAMA', 0.5, 0.5, 'pcs', 7),
  ('KSM', 'Ramen Toripaitan Standar', 'JMRKUPING', 0.01, 10.0, 'gr', 8),
  ('KSM', 'Ramen Toripaitan Standar', 'PKCY', 5.0, 5.0, 'gr', 9),
  ('KSM', 'Ramen Toripaitan Standar', 'DBWG', 4.0, 4.0, 'gr', 10),
  ('KSM', 'Ramen Truffle', 'SHIOTARE', 11.0, 11.0, 'ml', 0),
  ('KSM', 'Ramen Truffle', 'SHOYUTARE', 11.0, 11.0, 'ml', 1),
  ('KSM', 'Ramen Truffle', 'BTRUFWHITE', 2.0, 2.0, 'gr', 2),
  ('KSM', 'Ramen Truffle', 'BTRUFBLACK', 2.0, 2.0, 'gr', 3),
  ('KSM', 'Ramen Truffle', 'TRUFOIL', 1.0, 1.0, 'ml', 4),
  ('KSM', 'Ramen Truffle', 'CREMPREM', 4.0, 4.0, 'gr', 5),
  ('KSM', 'Ramen Truffle', 'MINDBWG', 5.0, 5.0, 'ml', 6),
  ('KSM', 'Ramen Truffle', 'MIE', 0.07, 70.0, 'gr', 7),
  ('KSM', 'Ramen Truffle', 'JAGUNG', 0.01, 10.0, 'gr', 8),
  ('KSM', 'Ramen Truffle', 'JMRKUPING', 0.01, 10.0, 'gr', 9),
  ('KSM', 'Ramen Truffle', 'DBWG', 4.0, 4.0, 'gr', 10),
  ('KSM', 'Ramen Truffle', 'PKCY', 5.0, 5.0, 'gr', 11),
  ('KSM', 'Ramen Truffle', 'AJITAMA', 0.5, 0.5, 'pcs', 12),
  ('KSM', 'Stadard Dry Ramen', 'MIE', 0.07, 70.0, 'gr', 0),
  ('KSM', 'Stadard Dry Ramen', 'BPAITAN', 0.005, 5.0, 'gr', 1),
  ('KSM', 'Stadard Dry Ramen', 'GARLICPWD', 2.0, 2.0, 'gr', 2),
  ('KSM', 'Stadard Dry Ramen', 'KECAM', 0.008333, 5.0, 'ml', 3),
  ('KSM', 'Stadard Dry Ramen', 'JAGUNG', 0.01, 10.0, 'gr', 4),
  ('KSM', 'Stadard Dry Ramen', 'JMRKUPING', 0.01, 10.0, 'gr', 5),
  ('KSM', 'Stadard Dry Ramen', 'DBWG', 4.0, 4.0, 'gr', 6),
  ('KSM', 'Stadard Dry Ramen', 'PKCY', 5.0, 5.0, 'gr', 7),
  ('KSM', 'Strawberry Kisamatcha Lattte', 'MATCHACER', 3.0, 3.0, 'gr', 0),
  ('KSM', 'Strawberry Kisamatcha Lattte', 'SUSFRES', 0.14, 140.0, 'ml', 1),
  ('KSM', 'Strawberry Kisamatcha Lattte', 'SStwb', 30.0, 30.0, 'gr', 2),
  ('KSM', 'Teh Tarik', 'TMTT', 1.0, 1.0, 'pcs', 0),
  ('KSM', 'Teh Tarik', 'GULCAIR', 5.0, 5.0, 'ml', 1),
  ('KSM', 'Tori Rice', 'GIMBORI', 5.0, 5.0, 'gr', 0),
  ('KSM', 'Ubee Coffe Latte', 'SKM', 0.02, 20.0, 'gr', 0),
  ('KSM', 'Ubee Coffe Latte', 'SUSFRES', 0.08, 80.0, 'ml', 1),
  ('KSM', 'Ubee Creamy Thaitea', 'SKM', 0.02, 20.0, 'gr', 0),
  ('KSM', 'Ubee Creamy Thaitea', 'POWTT', 15.0, 15.0, 'gr', 1),
  ('KSM', 'Ubee Creamy Thaitea', 'CREMPREM', 30.0, 30.0, 'gr', 2),
  ('KSM', 'Ubee Creamy Thaitea', 'SEAFOAM', 30.0, 30.0, 'gr', 3),
  ('KSM', 'Ubee Creamy Thaitea', 'CRUMBLE', 10.0, 10.0, 'gr', 4)
) as v(lokasi, nama, kode, qty, qty_input, satuan_input, urut)
join public.inv_menus m on m.business_id = 'e23ed572-234c-4995-acad-fa6bff7c58d2' and m.lokasi = v.lokasi and public.inv_norm(m.nama) = public.inv_norm(v.nama)
join public.inv_items i on i.business_id = m.business_id and i.kode = v.kode
where not exists (select 1 from public.inv_menu_lines x where x.menu_id = m.id and x.item_id = i.id);

insert into public.inv_menu_aliases (business_id, lokasi, nama_pos, nama_norm, menu_id)
select m.business_id, v.lokasi, v.nama_pos, public.inv_norm(v.nama_pos), m.id from (values
  ('KSM', 'Corn Milk', 'Corn Milk'),
  ('KSM', 'Corn Milk Coffee Latte', 'Corn Milk Coffe Latte'),
  ('KSM', 'Corn Milk Matcha Cloud', 'Corn Milk Matcha'),
  ('KSM', 'Ubee Coffee Latte', 'Ubee Coffe Latte'),
  ('KSM', 'Ubee Coffee Latte Foam', 'Ubee Coffe Latte'),
  ('KSM', 'Ubee Creamy Thai Tea', 'Ubee Creamy Thaitea'),
  ('KSM', 'Lemon Tea', 'Lemontea'),
  ('KSM', 'Lychee Ice', 'Leci Ice'),
  ('KSM', 'Mango ice', 'Manggo Ice'),
  ('KSM', 'Orange ice', 'Orange Ice'),
  ('KSM', 'Teh Manis', 'Teh Manis'),
  ('KSM', 'Teh Tarik', 'Teh Tarik'),
  ('KSM', 'Strawberry Kisamatcha Latte', 'Strawberry Kisamatcha Lattte'),
  ('KBU', 'Caramel Latte', 'Coffe Latte Caramel'),
  ('KBU', 'Hazelnut Latte', 'Coffe Latte Halzenut'),
  ('KBU', 'Vanilla Latte', 'Coffe Latte Vanila'),
  ('KBU', 'Blue Curacao Mojito', 'Mojito Blue Coracao'),
  ('KBU', 'Lychee Mojito', 'Mojito Leci'),
  ('KBU', 'Melon Mojito', 'Mojito Melon'),
  ('KBU', 'Strawberry Mojito', 'Mojito Strawberry'),
  ('KBU', 'Milkshake Avocado', 'Milkshake Avocado'),
  ('KBU', 'Milkshake Red Velvet', 'Milkshake Red Velvet'),
  ('KBU', 'Milkshake Taro', 'Milkshake Taro'),
  ('KBU', 'Kopi Susu Burma', 'Kopsus Burma'),
  ('KBU', 'Green Tea', 'Green Tea'),
  ('KBU', 'Lemon Tea', 'Lemon Tea'),
  ('KBU', 'Lychee Tea', 'Leci Tea'),
  ('KBU', 'Thai Tea', 'Thai Tea'),
  ('KBU', 'Lychee Yakult', 'Leci Yakult'),
  ('KSM', 'Dimsum Mentai isi 5', 'Dimsum Mentai'),
  ('KSM', 'Enoki Takiage', 'Enoki Takiage'),
  ('KSM', 'Gyoza Mentai', 'Gyoza Mentai'),
  ('KSM', 'Shukaku Milk Puding', 'Shukaku Puding'),
  ('KSM', 'Beef Yakiniku Donburi', 'Beef Yakiniku Donburi'),
  ('KSM', 'Atomic Spicy Black Noodles', 'Ramen Atomic'),
  ('KSM', 'Cheese Creamy Ramen', 'Ramen Chesee Creamy'),
  ('KSM', 'Tantamen Spicy Ramen', 'Ramen Tantamen'),
  ('KSM', 'Truffle Ramen', 'Ramen Truffle'),
  ('KSM', 'Standar Madara', 'Ramen Madara Standar'),
  ('KSM', 'Standar Original Curry', 'Ramen Curry Original'),
  ('KSM', 'Standar Shoyu', 'Ramen Shoyu Standar'),
  ('KSM', 'Standar Spicy Curry', 'Ramen Curry Spicy'),
  ('KSM', 'Standar Spicy ToriPaitan', 'Ramen Toripaitan Standar'),
  ('KSM', 'Standar ToriPaitan', 'Ramen Toripaitan Standar'),
  ('KSM', 'Standard Dry Ramen', 'Stadard Dry Ramen'),
  ('KSM', 'Standard Hashirama', 'Ramen Hashirama Standar'),
  ('KSM', 'Chicken Katsu', 'Chicken Katsu'),
  ('KBU', 'Kulit Goreng', 'Kulit Krispi'),
  ('KBU', 'Bebek Paha', 'Panas Bebek'),
  ('KBU', 'Dimsum Mentai (6)', 'Dimsum Mentai'),
  ('KBU', 'Gyoza Mentai isi 6', 'Gyoza Mentai'),
  ('KBU', 'Kentang Goreng Bude', 'FF Normal'),
  ('KBU', 'Otak-Otak', 'Otak-otak'),
  ('KBU', 'Pisang Goreng Keju Susu', 'Pisang Goreng Keju'),
  ('KBU', 'Pisang Goreng Pasir', 'Pisang Goreng Pasir'),
  ('KBU', 'Platter Premium', 'Plater Premium'),
  ('KBU', 'Platter Standar', 'Plater Standar'),
  ('KBU', 'Tahu Cabe Garam', 'Tahu Cabe Garam'),
  ('KBU', 'Ayam Bawang Putih', 'Lauk Ayam Baput'),
  ('KBU', 'Cobek Nila', 'Lauk Nila Cobek'),
  ('KBU', 'Jukut Goreng', 'Jukut Goreng'),
  ('KBU', 'Jukut Goreng Bojot', 'Jukut Goreng'),
  ('KBU', 'Kol Goyeng', 'Kol Goreng'),
  ('KBU', 'Pecok Katel', 'Pecok Katel'),
  ('KBU', 'Telur Kribo', 'Lauk Telor Kribo'),
  ('KBU', 'Nasi Tempong Ayam Bawang Putih', 'Tempong Ayam Baput'),
  ('KBU', 'Nasi Tempong Bebek', 'Tempong Bebek'),
  ('KBU', 'Madura Ayam Baput', 'Panas Ayam Baput Madura'),
  ('KBU', 'Madura Bebek Dada', 'Lauk Bebek Madura'),
  ('KBU', 'Madura Bebek Paha', 'Panas Bebek Madura'),
  ('KBU', 'Panas Ayam Bawang Putih', 'Panas Ayam Baput'),
  ('KBU', 'Panas Bebek Muda Dada', 'Panas Bebek'),
  ('KBU', 'Panas Lele', 'Panas Lele'),
  ('KBU', 'Panas Nila', 'Panas Nila'),
  ('KBU', 'Nasi Pedas Kemangi', 'Nasi Kemangi Pedas'),
  ('KBU', 'Nasi Rempah', 'Nasi Rempah'),
  ('KBU', 'Chicken Katsu Rice', 'Katsu Ricebowl'),
  ('KBU', 'Rice Bowl Ayam Kemangi', 'Ayam Kemangi Ricebowl'),
  ('KBU', 'Ricebowl Cumi Cabai Hijau', 'Cumi Ijo Ricebowl')
) as v(lokasi, nama_pos, resep)
join public.inv_menus m on m.business_id = 'e23ed572-234c-4995-acad-fa6bff7c58d2' and m.lokasi = v.lokasi and public.inv_norm(m.nama) = public.inv_norm(v.resep)
on conflict (business_id, lokasi, nama_norm) do nothing;

commit;
