-- Seed daftar SO per outlet (nama & satuan persis seperti laporan WA staf, 26 Sep 2026).
-- Jalankan SETELAH inventory_items_nusa_food.sql dan migrasi 20260927120000_inventory_so_template.sql.
-- isi = jumlah satuan master per 1 satuan SO; null = konversi belum diketahui (qty disimpan apa adanya, nilai Rp 0).
-- Aman dijalankan ulang.

begin;

-- 1) Bahan/setengah jadi baru yang muncul di laporan WA tapi belum ada di Master_Bahan (modal 0 — isi di Kelola).
insert into public.inv_items (business_id, kode, nama, kategori, tipe, satuan, harga, lokasi, min_stok, catatan)
select 'e23ed572-234c-4995-acad-fa6bff7c58d2'::uuid, v.* from (values
  ('MINIWONTON', 'Mini Wonton', 'Frozen', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('SOSSOLO', 'Sosis Solo (porsi)', 'Frozen', 'setengah_jadi', 'porsi', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('KULKRISPI', 'Kulit Krispi', 'Protein', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('TAHUCG', 'Tahu Cabe Garam (porsi)', 'Protein', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('AMPELA', 'Ampela', 'Protein', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('USUS', 'Usus', 'Protein', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('AYMSUWIR', 'Ayam Suwir', 'Protein', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('SRPYUZU', 'Sirup Yuzu', 'Beverage', 'bahan', 'ml', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('SRPELDER', 'Sirup Elderflower', 'Beverage', 'bahan', 'ml', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('SRPHONEY', 'Sirup Honey', 'Beverage', 'bahan', 'ml', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('SRPBUTTER', 'Sirup Butterscotch', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('SPRTWL', 'Sprite Waterlemon', 'Beverage', 'bahan', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('CRMJAVA', 'Creamer Javaland', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('GLACPREM', 'Gula Aren Cair Premium', 'Bumbu', 'bahan', 'ml', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('KOPIMURREL', 'Kopi Biji Murrel', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('KOPIHADE', 'Kopi Biji Hade', 'Beverage', 'bahan', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('SUSOUTSIDE', 'Susu Outside Barista', 'Beverage', 'bahan', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('REGAL', 'Biskuit Regal', 'Beverage', 'bahan', 'pax', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('JAMPEACH', 'Selai Peach Gold', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('JAMROSE', 'Selai Rose & Cranberry', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('JAMPASSION', 'Selai Passion Fruit', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('JAMDELFRU', 'Selai Strawberry Delfru', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('SAUCESALTED', 'Sauce Salted Caramel', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('LEMON', 'Buah Lemon', 'Sayur', 'bahan', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('YAKULT', 'Yakult', 'Beverage', 'bahan', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('JRKPERAS', 'Jeruk Peras', 'Sayur', 'bahan', 'pcs', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('LEMONKRG', 'Lemon Kering', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('JERUKKRG', 'Jeruk Kering', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KBU']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('MIE', 'Mie Ramen', 'Karbo', 'bahan', 'kg', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('MIEUDON', 'Mie Udon', 'Karbo', 'bahan', 'pcs', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('MIEHITAM', 'Mie Hitam', 'Karbo', 'bahan', 'kg', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('GIMBORI', 'Gimbori Tabur', 'Bumbu', 'bahan', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('WIJEN', 'Biji Wijen', 'Bumbu', 'bahan', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('KONBU', 'Konbu', 'Bumbu', 'bahan', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('SHITAKE', 'Jamur Shitake', 'Sayur', 'bahan', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('BTANTAMEN', 'Bumbu Tantamen', 'Bumbu', 'setengah_jadi', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('BTRUFWHITE', 'Bumbu Truffle White', 'Bumbu', 'setengah_jadi', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('BTRUFBLACK', 'Bumbu Truffle Black', 'Bumbu', 'setengah_jadi', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('BATOMIC', 'Bumbu Atomic', 'Bumbu', 'setengah_jadi', 'kg', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('BPAITAN', 'Bumbu Paitan', 'Bumbu', 'setengah_jadi', 'kg', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('BSHOYU', 'Bumbu Shoyu', 'Bumbu', 'setengah_jadi', 'ml', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('BMADARA', 'Bumbu Madara', 'Bumbu', 'setengah_jadi', 'kg', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('BHASHIRAMA', 'Bumbu Hashirama', 'Bumbu', 'setengah_jadi', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('CURRYORI', 'Curry Original', 'Bumbu', 'setengah_jadi', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('CURRYSPICY', 'Curry Spicy', 'Bumbu', 'setengah_jadi', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('CHILIOIL', 'Chili Oil', 'Bumbu', 'setengah_jadi', 'l', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('CHASHU', 'Ayam Chashu', 'Protein', 'setengah_jadi', 'kg', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('AYMTABUR', 'Ayam Tabur', 'Protein', 'setengah_jadi', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('AJITAMA', 'Telur Ajitama', 'Protein', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('JAGUNG', 'Jagung Kupas', 'Sayur', 'bahan', 'kg', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('JMRKUPING', 'Jamur Kuping', 'Sayur', 'bahan', 'kg', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('CORNRIBS', 'Cornribs', 'Frozen', 'setengah_jadi', 'porsi', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('GYOZA', 'Gyoza', 'Frozen', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('DIMSUM', 'Dimsum', 'Frozen', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('PUDVAN', 'Shukaku Pudding Vanilla', 'Dessert', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('PUDTARO', 'Shukaku Pudding Taro', 'Dessert', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('PUDMATCHA', 'Shukaku Pudding Matcha', 'Dessert', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('ENOKI', 'Enoki Takiage', 'Frozen', 'setengah_jadi', 'porsi', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('EKADO', 'Ekado', 'Frozen', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('KRGRB', 'Karage Rice Bowl (siap)', 'Protein', 'setengah_jadi', 'porsi', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('EBIFURAI', 'Ebi Furai', 'Frozen', 'bahan', 'pcs', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('EDAMAME', 'Edamame', 'Sayur', 'bahan', 'porsi', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('MATCHACER', 'Matcha Ceremonial', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('OCHA', 'Serbuk Ocha', 'Beverage', 'bahan', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('CORNMILK', 'Cornmilk', 'Beverage', 'setengah_jadi', 'ml', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('UBEE', 'Ubee', 'Beverage', 'setengah_jadi', 'gr', 0.0, array['GDG', 'KSM']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('DIMSUMGRG', 'Dimsum Goreng Keju', 'Frozen', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'SMT']::text[], 0.0, 'Baru dari laporan SO WA — isi modal'),
  ('UDANGKEJU', 'Udang Keju', 'Frozen', 'setengah_jadi', 'pcs', 0.0, array['GDG', 'SMT']::text[], 0.0, 'Baru dari laporan SO WA — isi modal')
) as v(kode, nama, kategori, tipe, satuan, harga, lokasi, min_stok, catatan)
on conflict (business_id, kode) do nothing;

-- 2) Pastikan bahan lama terdaftar di outlet yang meng-SO-nya.
update public.inv_items i set lokasi = (select array_agg(distinct x order by x) from unnest(i.lokasi || v.lok) x), updated_at = now()
from (values
  ('ATOOM', array['KSM']::text[]),
  ('AYMBPT', array['KBU']::text[]),
  ('AYMBSR', array['KBU']::text[]),
  ('AYMKMG', array['KBU']::text[]),
  ('AYMKMPNG', array['KBU']::text[]),
  ('AYMRGLR', array['KBU']::text[]),
  ('BBK', array['KBU']::text[]),
  ('BEEF', array['KSM']::text[]),
  ('BRS', array['KBU']::text[]),
  ('CLEO', array['KBU']::text[]),
  ('CMIJO', array['KBU']::text[]),
  ('CREMPREM', array['KBU', 'KSM']::text[]),
  ('CRNG', array['KBU']::text[]),
  ('CRUMBLE', array['KBU']::text[]),
  ('DBWG', array['KSM']::text[]),
  ('DIMSUM', array['SMT']::text[]),
  ('EVAPORASI', array['KBU']::text[]),
  ('FRTEA', array['KSM']::text[]),
  ('GLAB', array['KBU']::text[]),
  ('GLAC', array['KBU']::text[]),
  ('GULCAIR', array['KBU']::text[]),
  ('GYOZA', array['SMT']::text[]),
  ('IKNLL', array['KBU']::text[]),
  ('IKNNL', array['KBU']::text[]),
  ('JKL', array['KBU']::text[]),
  ('JKUT', array['KBU']::text[]),
  ('KEJUKER', array['KSM']::text[]),
  ('KNTG', array['KBU']::text[]),
  ('KRGE', array['KBU', 'KSM']::text[]),
  ('KTSU', array['KBU', 'KSM']::text[]),
  ('LCIKLNG', array['KBU']::text[]),
  ('LPTN LMN', array['KSM']::text[]),
  ('MACHIATO CC', array['KSM']::text[]),
  ('MILO', array['KSM']::text[]),
  ('MINGOR', array['KBU']::text[]),
  ('MISO', array['KSM']::text[]),
  ('Nori', array['KSM']::text[]),
  ('OTKOTK', array['KBU']::text[]),
  ('PKCY', array['KSM']::text[]),
  ('POWAVCD', array['KBU']::text[]),
  ('POWGT', array['KBU']::text[]),
  ('POWHZLNT', array['KBU']::text[]),
  ('POWLT', array['KBU']::text[]),
  ('POWLT2', array['KBU']::text[]),
  ('POWMTCH', array['KBU', 'KSM']::text[]),
  ('POWRV', array['KBU']::text[]),
  ('POWTR', array['KBU']::text[]),
  ('POWTT', array['KBU', 'KSM']::text[]),
  ('PP', array['KBU']::text[]),
  ('PRIMA', array['KSM']::text[]),
  ('PS', array['KBU']::text[]),
  ('SATER', array['KSM']::text[]),
  ('SATIR', array['KSM']::text[]),
  ('SKM', array['KBU']::text[]),
  ('SLSH', array['KBU']::text[]),
  ('SPRTKCL', array['KBU']::text[]),
  ('SRPBC', array['KBU']::text[]),
  ('SRPCRML', array['KBU']::text[]),
  ('SRPHZNT', array['KBU']::text[]),
  ('SRPLCH', array['KSM']::text[]),
  ('SRPLCMJN', array['KBU']::text[]),
  ('SRPLMN', array['KBU']::text[]),
  ('SRPMLN', array['KBU']::text[]),
  ('SRPMNGG', array['KBU', 'KSM']::text[]),
  ('SRPORNG', array['KBU', 'KSM']::text[]),
  ('SRPSTDCRML', array['KBU']::text[]),
  ('SRPSTRWB', array['KBU', 'KSM']::text[]),
  ('SRPVNL', array['KBU', 'KSM']::text[]),
  ('SStwb', array['KBU']::text[]),
  ('SUSFRES', array['KBU']::text[]),
  ('Sea', array['KBU']::text[]),
  ('TBTLKC', array['KSM']::text[]),
  ('TBTLPSTK', array['KSM']::text[]),
  ('TMTT', array['KSM']::text[]),
  ('UDNG', array['KSM']::text[])
) as v(kode, lok)
where i.business_id = 'e23ed572-234c-4995-acad-fa6bff7c58d2' and i.kode = v.kode and not (i.lokasi @> v.lok);

-- 3) Template SO per lokasi.
insert into public.inv_so_template (business_id, lokasi, item_id, label, grup, urut, satuan_so, isi, catatan)
select i.business_id, v.lokasi, i.id, v.label, v.grup, v.urut, v.satuan_so, v.isi, v.catatan
from (values
  ('KBU', 'BRS', 'Beras', 'Dapur', 10, 'karung', 25.0::numeric, null),
  ('KBU', 'MINGOR', 'Minyak Goreng', 'Dapur', 20, 'pouch', null::numeric, 'Pouch 2 L? (2L/Pouch)'),
  ('KBU', 'AYMRGLR', 'Ayam reg', 'Dapur', 30, 'pcs', 1.0::numeric, null),
  ('KBU', 'AYMBSR', 'Ayam besar', 'Dapur', 40, 'pcs', 1.0::numeric, null),
  ('KBU', 'BBK', 'Bebek', 'Dapur', 50, 'pcs', 1.0::numeric, null),
  ('KBU', 'IKNLL', 'Lele', 'Dapur', 60, 'ekor', 1.0::numeric, null),
  ('KBU', 'IKNNL', 'Nila', 'Dapur', 70, 'ekor', 1.0::numeric, null),
  ('KBU', 'AYMBPT', 'Ayam Baput', 'Dapur', 80, 'pcs', 1.0::numeric, null),
  ('KBU', 'KTSU', 'Katsu', 'Dapur', 90, 'pcs', 1.0::numeric, null),
  ('KBU', 'KRGE', 'Karage', 'Dapur', 100, 'pcs', null::numeric, 'Master gr — 1 pcs karage = ? gr'),
  ('KBU', 'JKUT', 'Jukut', 'Dapur', 110, 'porsi', 1.0::numeric, null),
  ('KBU', 'AYMKMG', 'Ayam kemangi', 'Dapur', 120, 'pcs', null::numeric, 'Master gr — 1 pcs = ? gr'),
  ('KBU', 'CMIJO', 'Cumi cb ijo', 'Dapur', 130, 'pcs', null::numeric, 'Master gr — 1 pcs = ? gr'),
  ('KBU', 'CRNG', 'Cireng', 'Dapur', 140, 'pcs', 1.0::numeric, 'Master bks — anggap 1 pcs = 1 bks?'),
  ('KBU', 'KNTG', 'FF', 'Dapur', 150, 'pcs', null::numeric, 'FF 1 pcs = berapa gr kentang?'),
  ('KBU', 'OTKOTK', 'Otak-otak', 'Dapur', 160, 'pcs', 1.0::numeric, null),
  ('KBU', 'PP', 'PP', 'Dapur', 170, 'pcs', 1.0::numeric, null),
  ('KBU', 'PS', 'PS', 'Dapur', 180, 'pcs', 1.0::numeric, null),
  ('KBU', 'MINIWONTON', 'Mini Wonton', 'Dapur', 190, 'pcs', 1.0::numeric, null),
  ('KBU', 'SOSSOLO', 'Sosis solo', 'Dapur', 200, 'porsi', 1.0::numeric, null),
  ('KBU', 'KULKRISPI', 'Kulit krispi', 'Dapur', 210, 'pcs', 1.0::numeric, null),
  ('KBU', 'JKL', 'Jengkol', 'Dapur', 220, 'pcs', null::numeric, 'Master gr — 1 pcs/porsi = ? gr'),
  ('KBU', 'TAHUCG', 'Tahu cabe garam', 'Dapur', 230, 'pcs', 1.0::numeric, null),
  ('KBU', 'AMPELA', 'Ampela', 'Dapur', 240, 'pcs', 1.0::numeric, null),
  ('KBU', 'USUS', 'Usus', 'Dapur', 250, 'pcs', 1.0::numeric, null),
  ('KBU', 'AYMSUWIR', 'Ayam suwir', 'Dapur', 260, 'pcs', 1.0::numeric, null),
  ('KBU', 'AYMKMPNG', 'Ayam kampung', 'Dapur', 270, 'pcs', 1.0::numeric, null),
  ('KBU', 'CLEO', 'Mineral', 'Bar', 280, 'pcs', 1.0::numeric, null),
  ('KBU', 'SKM', 'SKM', 'Bar', 290, 'gr', 0.001::numeric, null),
  ('KBU', 'SUSFRES', 'Fresh milk', 'Bar', 300, 'pcs', null::numeric, '1 pcs fresh milk = 1 L?'),
  ('KBU', 'SRPCRML', 'S. Caramel', 'Bar', 310, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPSTDCRML', 'S. Salted', 'Bar', 320, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPBC', 'S. Blue Curacao', 'Bar', 330, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPYUZU', 'S. Yuzu', 'Bar', 340, 'ml', 1.0::numeric, null),
  ('KBU', 'SRPHZNT', 'S. Hazelnut', 'Bar', 350, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPVNL', 'S. Vanilla', 'Bar', 360, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPLCMJN', 'S. Leci', 'Bar', 370, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPLMN', 'S. Lemon', 'Bar', 380, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPMNGG', 'S. Manggo', 'Bar', 390, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPORNG', 'S. Orange Juice', 'Bar', 400, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPSTRWB', 'S. Strawberry', 'Bar', 410, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPMLN', 'S. Melon', 'Bar', 420, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KBU', 'SRPELDER', 'S. Elderflower', 'Bar', 430, 'ml', 1.0::numeric, null),
  ('KBU', 'SRPHONEY', 'S. Honey', 'Bar', 440, 'ml', 1.0::numeric, null),
  ('KBU', 'SRPBUTTER', 'S. Butterscotch', 'Bar', 450, 'gr', 1.0::numeric, null),
  ('KBU', 'SPRTKCL', 'Sprite', 'Bar', 460, 'pcs', 1.0::numeric, null),
  ('KBU', 'SPRTWL', 'Water Lemon', 'Bar', 470, 'pcs', 1.0::numeric, null),
  ('KBU', 'CRMJAVA', 'Creamer JAVALAND (SMTRO)', 'Bar', 480, 'gr', 1.0::numeric, null),
  ('KBU', 'CREMPREM', 'Creamer Super Premium', 'Bar', 490, 'gr', 1.0::numeric, null),
  ('KBU', 'POWLT', 'P. Lemon Tea', 'Bar', 500, 'gr', 1.0::numeric, null),
  ('KBU', 'POWLT2', 'P. Leci Tea', 'Bar', 510, 'gr', 1.0::numeric, null),
  ('KBU', 'POWMTCH', 'P. Matcha', 'Bar', 520, 'gr', 1.0::numeric, null),
  ('KBU', 'POWHZLNT', 'P. Hazelnut Coklat', 'Bar', 530, 'gr', 1.0::numeric, null),
  ('KBU', 'POWRV', 'P. Red Velvet', 'Bar', 540, 'gr', 1.0::numeric, null),
  ('KBU', 'POWGT', 'Teh Green Tea', 'Bar', 550, 'gr', 1.0::numeric, null),
  ('KBU', 'POWAVCD', 'P. Avocado', 'Bar', 560, 'gr', 1.0::numeric, null),
  ('KBU', 'POWTT', 'Teh Thai Tea', 'Bar', 570, 'gr', 1.0::numeric, null),
  ('KBU', 'POWTR', 'P. Taro', 'Bar', 580, 'gr', 1.0::numeric, null),
  ('KBU', 'Sea', 'Sea salt', 'Bar', 590, 'gr', null::numeric, 'Master pcs — 1 pcs sea salt = ? gr'),
  ('KBU', 'CRUMBLE', 'Crumble', 'Bar', 600, 'gr', 1.0::numeric, null),
  ('KBU', 'GLAB', 'Aren BBK', 'Bar', 610, 'ml', null::numeric, 'Aren bubuk dihitung ml? atau gr?'),
  ('KBU', 'GLAC', 'Aren Cair', 'Bar', 620, 'ml', 1.0::numeric, 'Anggap 1 ml = 1 gr'),
  ('KBU', 'GLACPREM', 'Gulare aren cair', 'Bar', 630, 'ml', 1.0::numeric, 'Beda dengan Aren Cair?'),
  ('KBU', 'KOPIMURREL', 'Beans Murrel', 'Bar', 640, 'gr', 1.0::numeric, null),
  ('KBU', 'KOPIHADE', 'Beans Hade', 'Bar', 650, 'pcs', 1.0::numeric, 'pcs = pack berapa gr?'),
  ('KBU', 'EVAPORASI', 'Susu Evaporasi', 'Bar', 660, 'klg', 1.0::numeric, null),
  ('KBU', 'SUSOUTSIDE', 'Susu Outside', 'Bar', 670, 'pcs', 1.0::numeric, null),
  ('KBU', 'REGAL', 'Biskuit Regal', 'Bar', 680, 'pax', 1.0::numeric, null),
  ('KBU', 'GULCAIR', 'Gula Cair', 'Bar', 690, 'drigen', 5000.0::numeric, null),
  ('KBU', 'SStwb', 'Stroberi Jam GOLD', 'Bar', 700, 'gr', 1.0::numeric, null),
  ('KBU', 'JAMPEACH', 'Peach Jam GOLD', 'Bar', 710, 'gr', 1.0::numeric, null),
  ('KBU', 'JAMROSE', 'Rose & Cranberry JAM', 'Bar', 720, 'gr', 1.0::numeric, null),
  ('KBU', 'JAMPASSION', 'Passion Fruit JAM', 'Bar', 730, 'gr', 1.0::numeric, null),
  ('KBU', 'JAMDELFRU', 'Strawberry Jam Delfru', 'Bar', 740, 'gr', 1.0::numeric, null),
  ('KBU', 'SAUCESALTED', 'Sauce Salted', 'Bar', 750, 'gr', 1.0::numeric, null),
  ('KBU', 'LEMON', 'Buah Lemon', 'Bar', 760, 'pcs', 1.0::numeric, null),
  ('KBU', 'LCIKLNG', 'Buah Leci', 'Bar', 770, 'klg', 1.0::numeric, null),
  ('KBU', 'SLSH', 'Biji Selasih', 'Bar', 780, 'gr', 1.0::numeric, null),
  ('KBU', 'YAKULT', 'Yakult', 'Bar', 790, 'pcs', 1.0::numeric, null),
  ('KBU', 'JRKPERAS', 'Jeruk Peras', 'Bar', 800, 'pcs', 1.0::numeric, null),
  ('KBU', 'LEMONKRG', 'Lemon Kering', 'Bar', 810, 'gr', 1.0::numeric, null),
  ('KBU', 'JERUKKRG', 'Jeruk Kering', 'Bar', 820, 'gr', 1.0::numeric, null),
  ('KSM', 'MIE', 'Mie', 'Bahan', 10, 'kg', 1.0::numeric, null),
  ('KSM', 'MIEUDON', 'Mie Udon', 'Bahan', 20, 'pcs', 1.0::numeric, null),
  ('KSM', 'MIEHITAM', 'Mie Hitam', 'Bahan', 30, 'kg', 1.0::numeric, null),
  ('KSM', 'GIMBORI', 'Gimbori Tabur', 'Bahan', 40, 'gr', 1.0::numeric, null),
  ('KSM', 'WIJEN', 'Biji Wijen', 'Bahan', 50, 'gr', 1.0::numeric, null),
  ('KSM', 'KONBU', 'Konbu', 'Bahan', 60, 'gr', 1.0::numeric, null),
  ('KSM', 'SHITAKE', 'Jamur Shitake', 'Bahan', 70, 'gr', 1.0::numeric, null),
  ('KSM', 'SATER', 'Saori teriyaki', 'Bahan', 80, 'btl', null::numeric, 'Master L — 1 btl = ? L'),
  ('KSM', 'SATIR', 'Saori saus tiram', 'Bahan', 90, 'btl', null::numeric, 'Master L — 1 btl = ? L'),
  ('KSM', 'KEJUKER', 'Cheese Kerry', 'Bahan', 100, 'gr', 0.001::numeric, null),
  ('KSM', 'MACHIATO CC', 'Cheese Cream', 'Bahan', 110, 'gr', 0.001::numeric, null),
  ('KSM', 'ATOOM', 'Atoom', 'Bahan', 120, 'gr', null::numeric, 'Master pcs — 1 pcs atoom = ? gr'),
  ('KSM', 'CREMPREM', 'Krimmer', 'Bahan', 130, 'gr', 1.0::numeric, null),
  ('KSM', 'BTANTAMEN', 'Bumbu Tantamen', 'Bumbu', 140, 'gr', 1.0::numeric, null),
  ('KSM', 'BTRUFWHITE', 'B.Truffle White', 'Bumbu', 150, 'gr', 1.0::numeric, null),
  ('KSM', 'BTRUFBLACK', 'B.Truffle Black', 'Bumbu', 160, 'gr', 1.0::numeric, null),
  ('KSM', 'BATOMIC', 'Bumbu Atomic', 'Bumbu', 170, 'kg', 1.0::numeric, null),
  ('KSM', 'BPAITAN', 'Bumbu paitan', 'Bumbu', 180, 'kg', 1.0::numeric, null),
  ('KSM', 'BSHOYU', 'Bumbu shoyu', 'Bumbu', 190, 'ml', 1.0::numeric, null),
  ('KSM', 'MISO', 'Miso', 'Bumbu', 200, 'gr', 1.0::numeric, null),
  ('KSM', 'BMADARA', 'Bumbu Madara', 'Bumbu', 210, 'kg', 1.0::numeric, null),
  ('KSM', 'BHASHIRAMA', 'Bumbu Hashirama', 'Bumbu', 220, 'gr', 1.0::numeric, null),
  ('KSM', 'CURRYORI', 'Curry original', 'Bumbu', 230, 'gr', 1.0::numeric, null),
  ('KSM', 'CURRYSPICY', 'Curry Spicy', 'Bumbu', 240, 'gr', 1.0::numeric, null),
  ('KSM', 'CHILIOIL', 'Chili Oil', 'Bumbu', 250, 'l', 1.0::numeric, null),
  ('KSM', 'CHASHU', 'Ayam Chashu', 'Topping', 260, 'kg', 1.0::numeric, null),
  ('KSM', 'AYMTABUR', 'Ayam Tabur', 'Topping', 270, 'gr', 1.0::numeric, null),
  ('KSM', 'BEEF', 'Beef', 'Topping', 280, 'gr', 1.0::numeric, null),
  ('KSM', 'AJITAMA', 'Telor Ajitama', 'Topping', 290, 'pcs', 1.0::numeric, null),
  ('KSM', 'UDNG', 'Udang', 'Topping', 300, 'gr', 1.0::numeric, null),
  ('KSM', 'PKCY', 'Pakcoy', 'Topping', 310, 'kg', 1000.0::numeric, null),
  ('KSM', 'DBWG', 'Daun bawang', 'Topping', 320, 'gr', 1.0::numeric, null),
  ('KSM', 'JAGUNG', 'Jagung', 'Topping', 330, 'kg', 1.0::numeric, null),
  ('KSM', 'Nori', 'Nori Shusi', 'Topping', 340, 'lembar', null::numeric, 'Master ''pcs'' Rp105rb = 1 pack isi berapa lembar?'),
  ('KSM', 'JMRKUPING', 'Jamur kuping', 'Topping', 350, 'kg', 1.0::numeric, null),
  ('KSM', 'KRGE', 'Karage', 'Topping', 360, 'gr', 1.0::numeric, null),
  ('KSM', 'KTSU', 'Katsu', 'Topping', 370, 'pcs', 1.0::numeric, null),
  ('KSM', 'CORNRIBS', 'Cornribs', 'Ala Carte', 380, 'porsi', 1.0::numeric, null),
  ('KSM', 'GYOZA', 'Gyoza', 'Ala Carte', 390, 'porsi', null::numeric, '1 porsi gyoza = ? pcs (6?)'),
  ('KSM', 'DIMSUM', 'Dimsum', 'Ala Carte', 400, 'porsi', null::numeric, '1 porsi dimsum = ? pcs'),
  ('KSM', 'PUDVAN', 'Shukaku Milk Pudding Vanilla', 'Ala Carte', 410, 'pcs', 1.0::numeric, null),
  ('KSM', 'PUDTARO', 'Shukaku Milk Pudding Taro', 'Ala Carte', 420, 'pcs', 1.0::numeric, null),
  ('KSM', 'PUDMATCHA', 'Shukaku Milk Pudding Matcha', 'Ala Carte', 430, 'pcs', 1.0::numeric, null),
  ('KSM', 'ENOKI', 'Enoki', 'Ala Carte', 440, 'porsi', 1.0::numeric, null),
  ('KSM', 'EKADO', 'Ekado', 'Ala Carte', 450, 'pcs', 1.0::numeric, null),
  ('KSM', 'KRGRB', 'Karage Rice bowl', 'Ala Carte', 460, 'porsi', 1.0::numeric, null),
  ('KSM', 'EBIFURAI', 'Ebi Furai', 'Ala Carte', 470, 'pcs', 1.0::numeric, null),
  ('KSM', 'EDAMAME', 'Edamame', 'Ala Carte', 480, 'porsi', 1.0::numeric, null),
  ('KSM', 'TMTT', 'Teh tarik', 'Minuman', 490, 'sachet', 1.0::numeric, null),
  ('KSM', 'MILO', 'Milo', 'Minuman', 500, 'sachet', 1.0::numeric, null),
  ('KSM', 'LPTN LMN', 'Lemon tea', 'Minuman', 510, 'gr', null::numeric, 'Master pcs — 1 pcs Lipton = ? gr'),
  ('KSM', 'SRPLCH', 'Lychee ice', 'Minuman', 520, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KSM', 'SRPMNGG', 'Mango ice', 'Minuman', 530, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KSM', 'SRPORNG', 'Orange ice', 'Minuman', 540, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KSM', 'PRIMA', 'Air mineral', 'Minuman', 550, 'btl', 1.0::numeric, null),
  ('KSM', 'FRTEA', 'Fruit tea', 'Minuman', 560, 'btl', 1.0::numeric, null),
  ('KSM', 'TBTLKC', 'Teh botol kaca', 'Minuman', 570, 'btl', 1.0::numeric, null),
  ('KSM', 'TBTLPSTK', 'Teh botol plastik', 'Minuman', 580, 'btl', 1.0::numeric, null),
  ('KSM', 'POWMTCH', 'Pure Matcha', 'Minuman', 590, 'gr', 1.0::numeric, null),
  ('KSM', 'MATCHACER', 'Ceremony', 'Minuman', 600, 'gr', 1.0::numeric, null),
  ('KSM', 'SRPSTRWB', 'Sirup Strawberry', 'Minuman', 610, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KSM', 'SRPVNL', 'Sirup Vanilla', 'Minuman', 620, 'ml', null::numeric, 'Sirup: 1 botol = ? ml'),
  ('KSM', 'OCHA', 'Serbuk Ocha', 'Minuman', 630, 'gr', 1.0::numeric, null),
  ('KSM', 'CORNMILK', 'Cornmilk', 'Minuman', 640, 'ml', 1.0::numeric, null),
  ('KSM', 'UBEE', 'Ubee', 'Minuman', 650, 'gr', 1.0::numeric, null),
  ('KSM', 'POWTT', 'Thai Tea', 'Minuman', 660, 'gr', 1.0::numeric, null),
  ('SMT', 'DIMSUM', 'Dimsum', 'Stok', 10, 'pcs', 1.0::numeric, null),
  ('SMT', 'GYOZA', 'Gyoza', 'Stok', 20, 'pcs', 1.0::numeric, null),
  ('SMT', 'DIMSUMGRG', 'Dimsum Goreng', 'Stok', 30, 'pcs', 1.0::numeric, null),
  ('SMT', 'UDANGKEJU', 'Udang Keju', 'Stok', 40, 'pcs', 1.0::numeric, null)
) as v(lokasi, kode, label, grup, urut, satuan_so, isi, catatan)
join public.inv_items i on i.business_id = 'e23ed572-234c-4995-acad-fa6bff7c58d2' and i.kode = v.kode
on conflict (business_id, lokasi, label) do nothing;

commit;
