-- Seed master bahan dapur untuk bisnis Nusa Food (F&B) dari template_inventory_fnb_multi_outlet_v3 (Master_Bahan, status Aktif).
-- Lokasi diambil dari riwayat transfer/opname/barang masuk. Tipe setengah_jadi ditebak dari nama — koreksi di menu Kelola Bahan.
-- Harga = "Harga per Satuan Pakai" master; bahan bertanda "Cek konversi/harga" perlu dibetulkan (lihat file audit).
-- Aman dijalankan ulang (on conflict do nothing).

insert into public.inv_items (business_id, kode, nama, kategori, tipe, satuan, harga, lokasi, min_stok, catatan)
select 'e23ed572-234c-4995-acad-fa6bff7c58d2'::uuid, v.* from (values
  ('AYMSDG', 'Ayam Sedang', 'Protein', 'setengah_jadi', 'pcs', 7500.0, array['GDG', 'KBU']::text[], 40.0, null),
  ('AYMBSR', 'Ayam Besar', 'Protein', 'setengah_jadi', 'pcs', 9000.0, array['GDG', 'KBU']::text[], 20.0, null),
  ('AYMBPT', 'Ayam Baput', 'Protein', 'setengah_jadi', 'pcs', 5000.0, array['GDG', 'KBU']::text[], 25.0, 'Cek konversi/harga (hasil audit)'),
  ('AYMRGLR', 'Ayam Reguler', 'Protein', 'setengah_jadi', 'pcs', 5000.0, array['GDG', 'KBU']::text[], 25.0, 'Cek konversi/harga (hasil audit)'),
  ('AYMKMPNG', 'Ayam Kampung Lengket', 'Protein', 'setengah_jadi', 'pcs', 15000.0, array['GDG', 'KBU']::text[], 10.0, null),
  ('BBK', 'Bebek Ungkep', 'Protein', 'setengah_jadi', 'pcs', 15000.0, array['GDG', 'KBU']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('IKNLL', 'Ikan Lele Marinasi', 'Protein', 'setengah_jadi', 'pcs', 4000.0, array['GDG', 'KBU']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('IKNNL', 'Ikan Nila Marinasi', 'Protein', 'setengah_jadi', 'pcs', 7000.0, array['GDG', 'KBU']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('IKNPTN', 'Ikan Pindang patin', 'Protein', 'bahan', 'pcs', 10000.0, array['GDG']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('KTSU', 'Katsu', 'Protein', 'setengah_jadi', 'pcs', 10000.0, array['GDG']::text[], 30.0, 'Cek konversi/harga (hasil audit)'),
  ('KRGE', 'Karage', 'Protein', 'setengah_jadi', 'gr', 110.0, array['GDG', 'KBU']::text[], 20.0, 'Cek konversi/harga (hasil audit)'),
  ('AYMKMG', 'Ayam Kemangi', 'Protein', 'setengah_jadi', 'gr', 5000.0, array['GDG']::text[], 20.0, 'Cek konversi/harga (hasil audit)'),
  ('CMIJO', 'Cumi Cabe Ijo', 'Protein', 'setengah_jadi', 'gr', 7000.0, array['GDG']::text[], 20.0, 'Cek konversi/harga (hasil audit)'),
  ('JKL', 'Jengkol', 'Sayur', 'bahan', 'gr', 38.0, array['GDG']::text[], 20.0, 'Cek konversi/harga (hasil audit)'),
  ('TMPE', 'Tempe', 'Sayur', 'bahan', 'pcs', 500.0, array['GDG']::text[], 30.0, null),
  ('THU', 'Tahu', 'Sayur', 'bahan', 'pcs', 500.0, array['GDG']::text[], 30.0, null),
  ('SAMPMG', 'Sambal PMG 1 Tepak', 'Bumbu', 'setengah_jadi', 'pack', 70000.0, array['GDG']::text[], 1.0, null),
  ('SAMTEM', 'Sambal Tempong 1 Tepak', 'Bumbu', 'setengah_jadi', 'pack', 25000.0, array['GDG']::text[], 1.0, null),
  ('SAMBAW', 'Sambal Bawang 1 Tepak', 'Bumbu', 'setengah_jadi', 'pack', 20000.0, array['GDG']::text[], 1.0, null),
  ('BUMAD', 'Bumbu Madura 1 Tepak', 'Bumbu', 'setengah_jadi', 'pack', 30000.0, array['GDG']::text[], 1.0, null),
  ('TO', 'Tutug Oncom', 'Bumbu', 'setengah_jadi', 'pack', 30000.0, array['GDG']::text[], 1.0, null),
  ('BDJ', 'Bumbu Daun Jeruk', 'Bumbu', 'setengah_jadi', 'pack', 30000.0, array['GDG']::text[], 1.0, null),
  ('BRS', 'Beras 1 Sak', 'Bumbu', 'bahan', 'kg', 14000.0, array['GDG', 'KBU', 'KSM']::text[], 25.0, 'Cek konversi/harga (hasil audit)'),
  ('TLR', 'Telur', 'Bumbu', 'bahan', 'pcs', 1588.2353, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('GRM', 'Garam', 'Bumbu', 'bahan', 'pcs', 2000.0, array['GDG', 'KBU', 'KSM']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('GLP', 'Gula Pasir', 'Bumbu', 'bahan', 'kg', 19.0, array['GDG', 'KBU', 'KSM']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('GLA', 'Gula Aren', 'Bumbu', 'bahan', 'gr', 40.0, array['GDG']::text[], 3.0, null),
  ('GLAB', 'Gula Aren Bubuk', 'Bumbu', 'bahan', 'gr', 33.0, array['GDG', 'KBU', 'SMT']::text[], 3.0, null),
  ('GLAC', 'Gula Aren Cair', 'Bumbu', 'bahan', 'gr', 50.0, array['GDG', 'KBU']::text[], 3.0, null),
  ('MCN', 'Micin (ajinomoto)', 'Bumbu', 'bahan', 'gr', 32.5, array['GDG', 'KBU', 'KSM']::text[], 1000.0, 'Cek konversi/harga (hasil audit)'),
  ('MINGOR', 'Minyak Goreng', 'Bumbu', 'bahan', 'ml', 20.0, array['GDG', 'KBU', 'KSM']::text[], 12000.0, 'Cek konversi/harga (hasil audit)'),
  ('SAYAM', 'Sasa Ayam', 'Bumbu', 'bahan', 'gr', 29.5, array['GDG', 'KBU']::text[], 5000.0, null),
  ('ROYSAP', 'Royco Sapi', 'Bumbu', 'bahan', 'gr', 50.0, array['GDG', 'KBU']::text[], 500.0, null),
  ('RCK', 'Racik Ayam', 'Bumbu', 'bahan', 'pcs', 1600.0, array['GDG', 'KBU', 'KSM']::text[], 10.0, null),
  ('SATIR', 'Saori Tiram', 'Bumbu', 'bahan', 'l', 51000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('SATER', 'Saori Teriyaki', 'Bumbu', 'bahan', 'l', 53000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('KECIN', 'Kecap Ikan', 'Bumbu', 'bahan', 'btl', 36000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('LDA', 'Lada', 'Bumbu', 'bahan', 'pcs', 150.0, array['GDG']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('LDAKU', 'Ladaku', 'Bumbu', 'bahan', 'pcs', 1200.0, array['GDG', 'KBU']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('KMRI', 'Kemiri', 'Bumbu', 'bahan', 'gr', 25.0, array['GDG']::text[], 1.0, null),
  ('TRSI', 'Terasi', 'Bumbu', 'bahan', 'pcs', 400.0, array['GDG', 'KBU']::text[], 10.0, null),
  ('TRGU', 'Terigu', 'Bumbu', 'bahan', 'gr', 17.0, array['GDG', 'KBU', 'KSM']::text[], 5.0, null),
  ('TEPROT', 'Tepung Roti', 'Bumbu', 'bahan', 'gr', 15.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('TPMZN', 'Tepung Maizena', 'Bumbu', 'bahan', 'gr', 25.0, array['GDG', 'KSM']::text[], 1.0, null),
  ('BAPUTG', 'Bawang Putih Goreng', 'Bumbu', 'bahan', 'gr', 60.0, array['GDG', 'KBU', 'KSM']::text[], 2.0, null),
  ('TERAS', 'Tepung Beras', 'Bumbu', 'bahan', 'gr', 26.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('TAPIOKA', 'Tepung Tapioka', 'Bumbu', 'bahan', 'gr', 15.0, array['GDG', 'KBU', 'KSM']::text[], 5.0, null),
  ('PASVAN', 'Pasta Vanilli', 'Bumbu', 'bahan', 'btl', 9000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('BPOWDER', 'Baking Powder', 'Bumbu', 'bahan', 'btl', 6000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('KECMAS', 'Kecap Manis (indofood)', 'Bumbu', 'bahan', 'drigen', 250000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('SUSFRES', 'Susu freshmilk', 'Beverage', 'bahan', 'l', 16145.8333, array['GDG', 'KBU', 'KSM']::text[], 24.0, 'Cek konversi/harga (hasil audit)'),
  ('SKM', 'SKM Pillow', 'Beverage', 'bahan', 'kg', 21600.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 5.0, null),
  ('EVAPORASI', 'Susu Evaporasi', 'Beverage', 'bahan', 'klng', 16000.0, array['GDG', 'KBU']::text[], 5.0, null),
  ('KETUMB', 'Ketumbar Bubuk', 'Bumbu', 'bahan', 'gr', 40.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('SRPORNG', 'Sirup Orange Squash', 'Beverage', 'bahan', 'btl', 14000.0, array['GDG', 'KSM']::text[], 1.0, null),
  ('SRPFP', 'Sirup fruit punch', 'Beverage', 'bahan', 'btl', 25000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('SRPBC', 'Sirup Blue Curacao', 'Beverage', 'bahan', 'btl', 110000.0, array['GDG']::text[], 1.0, null),
  ('SRPCRML', 'Sirup Caramel', 'Beverage', 'bahan', 'btl', 65000.0, array['GDG']::text[], 2.0, null),
  ('SRPHZNT', 'Sirup Hazelnut', 'Beverage', 'bahan', 'btl', 65000.0, array['GDG']::text[], 2.0, null),
  ('SRPLMN', 'Sirup Lemon', 'Beverage', 'bahan', 'btl', 23000.0, array['GDG']::text[], 2.0, null),
  ('SRPLCH', 'Sirup Lychee squash', 'Beverage', 'bahan', 'btl', 14000.0, array['GDG', 'KBU', 'KSM']::text[], 3.0, null),
  ('SRPMNGG', 'Sirup manggo squash', 'Beverage', 'bahan', 'btl', 14000.0, array['GDG', 'KBU', 'KSM']::text[], 2.0, null),
  ('SRPMLN', 'Sirup Melon', 'Beverage', 'bahan', 'btl', 23000.0, array['GDG']::text[], 1.0, null),
  ('SRPPNDN', 'Sirup Pandan', 'Beverage', 'bahan', 'btl', 105000.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('SRPSTDCRML', 'Sirup Salted Caramel', 'Beverage', 'bahan', 'btl', 65000.0, array['GDG']::text[], 1.0, null),
  ('SRPSTRWB', 'Sirup Strawberry', 'Beverage', 'bahan', 'btl', 23000.0, array['GDG', 'KBU', 'KSM']::text[], 2.0, null),
  ('SRPSNKSTORNG', 'Sirup Sunkist Orange', 'Beverage', 'bahan', 'btl', 164000.0, array['GDG']::text[], 1.0, null),
  ('SRPLCMJN', 'Sirup leci marjan', 'Beverage', 'bahan', 'btl', 23000.0, array['GDG', 'KBU']::text[], 2.0, null),
  ('SRPVNL', 'Sirup Vanilla', 'Beverage', 'bahan', 'btl', 23000.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 3.0, null),
  ('POWAVCD', 'Powder Avocado', 'Beverage', 'bahan', 'gr', 80.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('POWGT', 'Powder Green Tea', 'Beverage', 'bahan', 'gr', 126.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('POWZENLT', 'Powder Zeenlate', 'Beverage', 'bahan', 'gr', 45.0, array['GDG', 'KBU']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('POWHZLNT', 'Powder Hazelnut Chocolate', 'Beverage', 'bahan', 'gr', 104.5, array['GDG', 'KBU']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('POWLT', 'Powder Lemon Tea', 'Beverage', 'bahan', 'gr', 70.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('POWLT2', 'Powder lychee tea', 'Beverage', 'bahan', 'gr', 65.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('POWMTCH', 'Powder Matcha', 'Beverage', 'bahan', 'gr', 126.0, array['GDG', 'KSM']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('POWRV', 'Powder Red Velvet', 'Beverage', 'bahan', 'gr', 95.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('POWTR', 'Powder Taro', 'Beverage', 'bahan', 'gr', 80.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('POWTT', 'Powder thai tea 1kg', 'Beverage', 'bahan', 'gr', 87.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('CREMPREM', 'Creamer Premium', 'Beverage', 'bahan', 'gr', 40.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('MACHIATO FOAM', 'Machiato Foam', 'Beverage', 'bahan', 'gr', 100.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('PRIMA', 'Prima Botol', 'Beverage', 'bahan', 'pcs', 1437.5, array['GDG', 'KBU', 'KSM']::text[], 72.0, null),
  ('TBTLKC', 'Teh Botol Kaca', 'Beverage', 'bahan', 'pcs', 3916.6667, array['GDG']::text[], 12.0, null),
  ('TBTLPSTK', 'Teh Botol Plastik', 'Beverage', 'bahan', 'pcs', 3500.0, array['GDG']::text[], 12.0, null),
  ('FRTEA', 'Fruit Tea Apel', 'Beverage', 'bahan', 'pcs', 3500.0, array['GDG', 'KSM']::text[], 12.0, null),
  ('FRTEB', 'Fruit Tea Blackcurent', 'Beverage', 'bahan', 'pcs', 3500.0, array['GDG', 'KSM']::text[], 12.0, null),
  ('MXTEAL', 'Maxtea Lemon Tea', 'Beverage', 'bahan', 'pcs', 1500.0, array['GDG', 'KSM']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('TMTT', 'TMT Tarik', 'Beverage', 'bahan', 'pcs', 27000.0, array['GDG', 'KBU', 'KSM']::text[], 10.0, null),
  ('CLEO', 'Cleo Botol', 'Beverage', 'bahan', 'pcs', 1604.1667, array['GDG', 'KBU', 'SMT']::text[], 120.0, 'Cek konversi/harga (hasil audit)'),
  ('SPRTKCL', 'Sprite Kecil', 'Beverage', 'bahan', 'pcs', 3333.3333, array['GDG', 'KBU']::text[], 12.0, null),
  ('SLSH', 'Biji Selasih', 'Bumbu', 'bahan', 'gr', 90.0, array['GDG']::text[], 100.0, 'Cek konversi/harga (hasil audit)'),
  ('SStwb', 'Selai Strawberry', 'Frozen', 'bahan', 'gr', 50.0, array['GDG', 'KBU', 'KSM']::text[], 1000.0, 'Cek konversi/harga (hasil audit)'),
  ('STRS', 'Soda Tanpa Rasa', 'Beverage', 'bahan', 'pcs', 5000.0, array['GDG', 'KBU']::text[], 12.0, 'Cek konversi/harga (hasil audit)'),
  ('KNTG', 'Kentang Normal', 'Frozen', 'bahan', 'pcs', 28.0, array['GDG', 'KBU']::text[], 10.0, null),
  ('OTKOTK', 'Otak-otak', 'Frozen', 'bahan', 'pcs', 500.0, array['GDG', 'KBU']::text[], 10.0, null),
  ('SOSDBD', 'Sosis Dobedoo', 'Frozen', 'bahan', 'pcs', 1000.0, array['GDG', 'KBU']::text[], 80.0, null),
  ('NGTMBL', 'Nuget Mabel', 'Frozen', 'bahan', 'pcs', 1000.0, array['GDG', 'KBU']::text[], 50.0, null),
  ('PP', 'Plater Premium', 'Frozen', 'setengah_jadi', 'bks', 12500.0, array['GDG', 'KBU']::text[], 10.0, null),
  ('PS', 'Plater Standar', 'Frozen', 'setengah_jadi', 'bks', 7500.0, array['GDG', 'KBU']::text[], 10.0, null),
  ('CRNG', 'Cireng Jadi', 'Frozen', 'bahan', 'bks', 2500.0, array['GDG']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('BWM', 'Bawang Merah', 'Bumbu', 'bahan', 'gr', 33.0, array['GDG']::text[], 2.0, null),
  ('BWP', 'Bawang Putih', 'Bumbu', 'bahan', 'gr', 43.0, array['GDG']::text[], 3.0, null),
  ('BWB', 'Bawang Bombay', 'Bumbu', 'bahan', 'gr', 38.0, array['GDG']::text[], 1.0, null),
  ('PKCY', 'Pakcoy', 'Sayur', 'bahan', 'gr', 18.0, array['GDG']::text[], 1.0, null),
  ('DBWG', 'Daun Bawang', 'Sayur', 'bahan', 'gr', 18.0, array['GDG']::text[], 1.0, null),
  ('LBU', 'Labu', 'Sayur', 'bahan', 'gr', 15.0, array['GDG']::text[], 1.0, null),
  ('KCPJ', 'Kacang Panjang', 'Sayur', 'bahan', 'gr', 13.0, array['GDG']::text[], 1.0, null),
  ('TERBEL', 'Terong belanda', 'Sayur', 'bahan', 'gr', 15.0, array['GDG']::text[], 1.0, null),
  ('SRH', 'Sereh', 'Bumbu', 'bahan', 'gr', 10.0, array['GDG']::text[], 15.0, null),
  ('JHE', 'Jahe', 'Bumbu', 'bahan', 'gr', 50.0, array['GDG']::text[], 1.0, null),
  ('LKS', 'Lengkuas', 'Bumbu', 'bahan', 'gr', 10.0, array['GDG']::text[], 1.0, null),
  ('KNYT', 'Kunyit', 'Bumbu', 'bahan', 'gr', 10.0, array['GDG']::text[], 1.0, null),
  ('KNCR', 'Kencur', 'Bumbu', 'bahan', 'gr', 32.0, array['GDG']::text[], 0.5, null),
  ('CRS', 'Cabai Rawit Setan', 'Bumbu', 'bahan', 'gr', 60.0, array['GDG']::text[], 3.0, null),
  ('CMK', 'Cabai Merah Keriting', 'Bumbu', 'bahan', 'gr', 60.0, array['GDG']::text[], 3.0, null),
  ('CKRG', 'Cabai Kering', 'Bumbu', 'bahan', 'gr', 80.0, array['GDG']::text[], 1.0, null),
  ('CJPN', 'Cabai Jepun', 'Bumbu', 'bahan', 'gr', 40.0, array['GDG']::text[], 1.0, null),
  ('CIJO', 'Cabai Ijo', 'Bumbu', 'bahan', 'gr', 20.0, array['GDG']::text[], 1.0, null),
  ('KNYTBBK', 'Kunyit bubuk', 'Bumbu', 'bahan', 'gr', 45.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('PARSLEY', 'Parsley Bubuk', 'Bumbu', 'bahan', 'gr', 115.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('CBBK', 'Cabe Bubuk', 'Bumbu', 'bahan', 'gr', 60.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('ANSTR', 'anisstar', 'Bumbu', 'bahan', 'gr', 250.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('KYMNS', 'kayu manis', 'Bumbu', 'bahan', 'gr', 100.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('PLA', 'Pala', 'Bumbu', 'bahan', 'gr', 200.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('KPULG', 'Kapulaga', 'Bumbu', 'bahan', 'gr', 200.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('CNGKH', 'Cengkeh', 'Bumbu', 'bahan', 'gr', 124.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('KLWK', 'Kluwek', 'Bumbu', 'bahan', 'gr', 28.0, array['GDG']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('KECAM', 'Kecap Anggur Manis', 'Bumbu', 'bahan', 'btl', 28000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('KECAS', 'Kecap Anggur Asin', 'Bumbu', 'bahan', 'btl', 20000.0, array['GDG', 'KSM']::text[], 1.0, null),
  ('JNKL', 'Jengkol', 'Bumbu', 'bahan', 'gr', 38.0, array['GDG']::text[], 1.0, null),
  ('JKUT', 'Jukut', 'Bumbu', 'bahan', 'pcs', 2500.0, array['GDG', 'KBU']::text[], 15.0, null),
  ('KJU', 'Keju', 'Bumbu', 'bahan', 'pcs', 15000.0, array['GDG', 'KBU']::text[], 2.0, 'Cek konversi/harga (hasil audit)'),
  ('KJUISI', 'Keju Isian ( cheesy )', 'Bumbu', 'bahan', 'gr', 150.0, array['GDG']::text[], 1.0, null),
  ('KULDIM', 'Kulit Dimsum', 'Frozen', 'bahan', 'pcs', 16000.0, array['GDG', 'KBU']::text[], 5.0, 'Cek konversi/harga (hasil audit)'),
  ('KULUM', 'Kulit Lumpia ( FINNA )', 'Frozen', 'bahan', 'pcs', 750.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('KULTAH', 'Kulit Tahu', 'Frozen', 'bahan', 'pcs', 700.0, array['GDG', 'KSM']::text[], 50.0, null),
  ('KLIR1000', 'Klir 1000ml', 'Kemasan', 'kemasan', 'pcs', 35000.0, array['GDG', 'KBU', 'KSM']::text[], 2.0, null),
  ('KLIR25', 'Klir 25ml', 'Kemasan', 'kemasan', 'pcs', 10000.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 3.0, null),
  ('KLIR35', 'Klir 35ml', 'Kemasan', 'kemasan', 'pcs', 13000.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 3.0, null),
  ('BOXRB', 'Box Rice Bowl', 'Kemasan', 'kemasan', 'pcs', 28000.0, array['GDG', 'KBU', 'SMT']::text[], 1.0, null),
  ('CUPTH', 'Cup Teh', 'Kemasan', 'kemasan', 'roll', 19000.0, array['GDG', 'KBU', 'KSM']::text[], 3.0, null),
  ('CUP12', 'Cup 12oz Oval', 'Kemasan', 'kemasan', 'roll', 24000.0, array['GDG', 'KSM']::text[], 2.0, null),
  ('LBM', 'Lunch Box M', 'Kemasan', 'kemasan', 'pcs', 630.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 4.0, null),
  ('LBS', 'Lunch Box S', 'Kemasan', 'kemasan', 'pcs', 535.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 4.0, null),
  ('MIKSAM', 'Mika Sambal', 'Kemasan', 'kemasan', 'pcs', 7000.0, array['GDG', 'KBU', 'KSM']::text[], 2.0, 'Cek konversi/harga (hasil audit)'),
  ('SEDTN', 'Sedotan', 'Kemasan', 'kemasan', 'pcs', 25000.0, array['GDG', 'KBU', 'KSM']::text[], 2.0, 'Cek konversi/harga (hasil audit)'),
  ('SUMPT', 'Sumpit Kayu', 'Kemasan', 'kemasan', 'pcs', 6300.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 2.0, 'Cek konversi/harga (hasil audit)'),
  ('PLSTKSGTG', 'Plastik Segitiga', 'Kemasan', 'kemasan', 'pcs', 9000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('SRNGPLSTK', 'Sarung Tangan Plastik', 'Kemasan', 'kemasan', 'pcs', 10000.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('KRTSBUNG', 'Kertas Nasi Bunga', 'Kemasan', 'kemasan', 'pcs', 24000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('GRPUBUAH', 'Garpu Buah', 'Kemasan', 'kemasan', 'pcs', 11000.0, array['GDG', 'KBU']::text[], 2.0, null),
  ('TSUKGGI', 'Tusuk Gigi', 'Kemasan', 'kemasan', 'pcs', 1850.0, array['GDG', 'KBU']::text[], 5.0, null),
  ('MIKSOS', 'Mika Sosis', 'Kemasan', 'kemasan', 'pcs', 20000.0, array['GDG', 'SMT']::text[], 1.0, null),
  ('SNDOKBBK', 'Sendok Bebek', 'Kemasan', 'kemasan', 'pcs', 8000.0, array['GDG']::text[], 1.0, null),
  ('SNDOKPLSTK', 'Sendok Makan Plastik', 'Kemasan', 'kemasan', 'pcs', 18000.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 1.0, null),
  ('SNDOKPDING', 'Sendok Puding', 'Kemasan', 'kemasan', 'pcs', 8000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('THERGE', 'Thermal Gede', 'Kemasan', 'kemasan', 'pcs', 28000.0, array['GDG', 'KBU', 'KSM']::text[], 2.0, null),
  ('THERCIL', 'Thermal Kecil', 'Kemasan', 'kemasan', 'pcs', 29000.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 2.0, null),
  ('KFC', 'Kertas KFC', 'Kemasan', 'kemasan', 'pcs', 8000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('KFCMOT', 'Kertas KFC Motif', 'Kemasan', 'kemasan', 'pcs', 9000.0, array['GDG']::text[], 1.0, null),
  ('KFCCEM', 'Kertas Cemilan', 'Kemasan', 'kemasan', 'pcs', 21000.0, array['GDG', 'KBU']::text[], 2.0, null),
  ('PSAMPAH', 'Plastik Sampah', 'Kemasan', 'kemasan', 'pcs', 24000.0, array['GDG', 'KBU', 'KSM']::text[], 2.0, null),
  ('UK30', 'Kresek Uk30', 'Kemasan', 'kemasan', 'pcs', 8500.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('UK24', 'Kresek Uk24', 'Kemasan', 'kemasan', 'pcs', 21500.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 2.0, null),
  ('UK15', 'Kresek Uk15', 'Kemasan', 'kemasan', 'pcs', 21500.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 2.0, null),
  ('1CUP', 'Kresek 1 Cup', 'Kemasan', 'kemasan', 'pcs', 8000.0, array['GDG', 'KBU', 'SMT']::text[], 1.0, null),
  ('2CUP', 'Kresek 2 Cup', 'Kemasan', 'kemasan', 'pcs', 9000.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 1.0, null),
  ('11x25', 'Plastik Es 11x25', 'Kemasan', 'kemasan', 'pcs', 12500.0, array['GDG', 'KBU', 'KSM']::text[], 2.0, null),
  ('Wraping', 'Wraping', 'Kemasan', 'kemasan', 'pcs', 0, array['GDG', 'KBU']::text[], 1.0, null),
  ('FOIL DIM', 'Alumunium Dimsum', 'Kemasan', 'kemasan', 'pcs', 1160.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 10.0, null),
  ('LBM BURI', 'Lunch Box Buriumah M', 'Kemasan', 'kemasan', 'pcs', 1100.0, array['GDG', 'KBU']::text[], 20.0, null),
  ('CUPBM', 'Cup Buriumah M', 'Kemasan', 'kemasan', 'roll', 32500.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 10.0, null),
  ('CUPBL', 'Cup Buriumah L', 'Kemasan', 'kemasan', 'roll', 32500.0, array['GDG', 'KBU']::text[], 10.0, null),
  ('CUPS', 'Cup Samtaro', 'Kemasan', 'kemasan', 'roll', 32500.0, array['GDG', 'KBU', 'SMT']::text[], 10.0, null),
  ('CUPKSM', 'Cup Kisamatcha', 'Kemasan', 'kemasan', 'roll', 32500.0, array['GDG', 'KBU', 'KSM']::text[], 10.0, null),
  ('TTUPCUP', 'Tutup Cup', 'Kemasan', 'kemasan', 'roll', 10750.0, array['GDG', 'KBU', 'KSM']::text[], 5.0, null),
  ('Seel', 'Cup Siller Polos', 'Kemasan', 'kemasan', 'pcs', 35000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('TISU', 'Tisu', 'Kemasan', 'kemasan', 'pcs', 2083.3333, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('LCIKLNG', 'Leci Kaleng', 'Beverage', 'bahan', 'pcs', 25000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('GULCAIR', 'Gula Cair', 'Bumbu', 'bahan', 'gr', 16.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('CRUMBLE', 'Crumble', 'Bumbu', 'bahan', 'gr', 80.0, array['GDG', 'KBU']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('MACHIATO CC', 'Machiato Cheese Cream', 'Bumbu', 'bahan', 'kg', 115000.0, array['GDG', 'KSM']::text[], 1.0, null),
  ('KEJUKER', 'Keju Kerry', 'Bumbu', 'bahan', 'kg', 125000.0, array['GDG', 'KSM']::text[], 1.0, null),
  ('ATOOM', 'Bubuk Atoom Bulan', 'Bumbu', 'bahan', 'pcs', 50000.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('LPTN LC', 'Lipton Leci', 'Bumbu', 'bahan', 'pcs', 45000.0, array['GDG', 'KBU']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('LPTN LMN', 'Lipton Lemon', 'Bumbu', 'bahan', 'pcs', 45000.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 1.0, 'Cek konversi/harga (hasil audit)'),
  ('THPOCI', 'Teh Poci', 'Bumbu', 'bahan', 'pcs', 3300.0, array['GDG', 'KBU', 'KSM']::text[], 10.0, null),
  ('MILO', 'Milo', 'Bumbu', 'bahan', 'pcs', 2000.0, array['GDG', 'KBU', 'KSM']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('SAMKOK', 'Sambal Finna Bangkok', 'Bumbu', 'bahan', 'pcs', 433.3333, array['GDG', 'KBU', 'SMT']::text[], 50.0, null),
  ('MAMAYO', 'Mayonaise Mamayo', 'Bumbu', 'bahan', 'kg', 22708.3333, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 6.0, null),
  ('KEWPIE', 'Mayonaise Kewpie', 'Bumbu', 'bahan', 'kg', 75000.0, array['GDG']::text[], 2.0, null),
  ('EGGS POW', 'Bubuk Puding eggs', 'Bumbu', 'bahan', 'kg', 85000.0, array['GDG']::text[], 1.0, null),
  ('DELTOM', 'Saus Tomat (delmonte)', 'Bumbu', 'bahan', 'kg', 34000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('DELCHIL', 'Saus Sambal (delmonte)', 'Bumbu', 'bahan', 'kg', 40000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('DELBBQ', 'Saus BBQ (delmonte)', 'Bumbu', 'bahan', 'kg', 42500.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('DELBPP', 'Saus Black Paper (delmonte)', 'Bumbu', 'bahan', 'kg', 45000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('GOURMET', 'Saus Super Pedas Gourmet', 'Bumbu', 'bahan', 'kg', 15000.0, array['GDG']::text[], 1.0, null),
  ('ABCASIN', 'Kecap Asin (ABC)', 'Bumbu', 'bahan', 'drigen', 85000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('MINJEN', 'Minyak Wijen', 'Bumbu', 'bahan', 'btl', 135000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('KNORAY', 'Knor Ayam', 'Bumbu', 'bahan', 'kg', 100000.0, array['GDG', 'KSM']::text[], 1.0, null),
  ('HOUSEORI', 'Kari Houseband Original', 'Bumbu', 'bahan', 'pcs', 165000.0, array['GDG', 'KSM']::text[], 1870.0, null),
  ('HOUSECHILI', 'Kari Houseband Spicy', 'Bumbu', 'bahan', 'pcs', 165000.0, array['GDG', 'KBU', 'KSM']::text[], 1870.0, null),
  ('MISO', 'Miso', 'Frozen', 'bahan', 'gr', 45.0, array['GDG']::text[], 2.0, 'Cek konversi/harga (hasil audit)'),
  ('MRIN', 'Mirin (Kokiman)', 'Bumbu', 'bahan', 'pcs', 97500.0, array['GDG', 'KBU', 'KSM']::text[], 2000.0, null),
  ('BEEF', 'Beef Slice', 'Frozen', 'bahan', 'gr', 112.0, array['GDG', 'KBU', 'KSM']::text[], 2000.0, 'Cek konversi/harga (hasil audit)'),
  ('UDNG', 'Udang Beku', 'Frozen', 'bahan', 'gr', 120.0, array['GDG', 'KBU', 'KSM']::text[], 2000.0, 'Cek konversi/harga (hasil audit)'),
  ('CKR', 'Ceker', 'Frozen', 'bahan', 'gr', 25.0, array['GDG', 'KBU', 'KSM']::text[], 2000.0, 'Cek konversi/harga (hasil audit)'),
  ('KECMBRNG', 'Kecombrang', 'Bumbu', 'bahan', 'gr', 45.0, array['GDG', 'KBU', 'KSM']::text[], 1000.0, 'Cek konversi/harga (hasil audit)'),
  ('MMALIME', 'Mama Lime', 'Cleaning', 'lainnya', 'pcs', 902.7778, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('HNDSOAP', 'Hand Soap', 'Cleaning', 'lainnya', 'drigen', 65000.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('DAIA', 'Daia', 'Cleaning', 'lainnya', 'pcs', 500.0, array['GDG', 'KBU', 'KSM']::text[], 12.0, 'Cek konversi/harga (hasil audit)'),
  ('DOWNY', 'Downy', 'Cleaning', 'lainnya', 'pcs', 500.0, array['GDG', 'KBU', 'KSM']::text[], 10.0, 'Cek konversi/harga (hasil audit)'),
  ('SOKLANTAI', 'SoKlin Lantai', 'Cleaning', 'lainnya', 'pcs', 500.0, array['GDG', 'KBU', 'KSM', 'SMT']::text[], 10.0, null),
  ('COLEK', 'Sabun Colek', 'Cleaning', 'lainnya', 'pcs', 5000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('SEERAK', 'Serabut Kawat', 'Cleaning', 'lainnya', 'pcs', 3000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('KARBOL', 'Karbol Toilet', 'Cleaning', 'lainnya', 'pcs', 25000.0, array['GDG', 'KBU', 'KSM']::text[], 1.0, null),
  ('SBUBUR', 'Sterefoam Bubur', 'Kemasan', 'kemasan', 'pcs', 400.0, array['GDG', 'KBU']::text[], 10.0, null),
  ('SBURGER', 'Sterefoam Burger', 'Kemasan', 'kemasan', 'pcs', 195.0, array['GDG', 'KBU']::text[], 10.0, null),
  ('LKBNKCL', 'Lakban 1 Jari', 'Kemasan', 'kemasan', 'pcs', 5400.0, array['GDG', 'KBU']::text[], 1.0, null),
  ('Wizie', 'Sabun Wizie', 'Cleaning', 'lainnya', 'pcs', 1000.0, array['GDG', 'KSM']::text[], 1.0, null),
  ('Sea', 'Sea Salt', 'Dry Goods', 'bahan', 'pcs', 55000.0, array['GDG']::text[], 1.0, null),
  ('10x20', 'Plastik 10x20 05', 'Kemasan', 'kemasan', 'pcs', 8000.0, array['GDG']::text[], 1.0, null),
  ('LBL', 'Lunch Box L', 'Kemasan', 'kemasan', 'pcs', 730.0, array['GDG', 'KBU']::text[], 50.0, null),
  ('Nori', 'Nori Sheet', 'Sayur/Aroma', 'bahan', 'pcs', 105000.0, array[]::text[], 1.0, null),
  ('Mc Lewis', 'Mc Lewis Chili', 'Bumbu', 'bahan', 'drigen', 75000.0, array[]::text[], 1.0, null)
) as v(kode, nama, kategori, tipe, satuan, harga, lokasi, min_stok, catatan)
on conflict (business_id, kode) do nothing;
